### ISSUE TITLE
Pictures with transparent background doen't looks good on the GitHub dark mode

### ISSUE THREAD

**Issue by pedrominatel** [espressif/esp-box#1]
The pictures don't look good when using the GH dark mode theme.

![image](https://user-images.githubusercontent.com/274658/138664433-50cd7e44-6926-486a-a571-7990ba0a0c5f.png)

Consider using images with white background.

**Comment by leeebo** [comment]
@pedrominatel Thanks for your feedback, Github dark mode is supported now.

**Comment by pedrominatel** [comment]
It looks better now @leeebo!
