### ISSUE TITLE
[After playing well for one day ...] A device attached to the system is not functioning

### ISSUE THREAD

**Issue by BigJohnn** [espressif/esp-box#10]
Hi, 
    I have followed some tutorials, and do 
> idf.py -p COMX build flash

... things go well.
But one day later, when I open my PC again, trying to run 

> idf.py -p COMX monitor

I got

`serial.serialutil.SerialException:` Cannot configure port, something went wrong. Original message: PermissionError(13, 'A device attached to the system is not functioning.', None, 31)`

I have tried to change my COM number or uninstall&&reinstall the driver of the serial, but nothing works T.T
Any ideas? Thx.
P.S. win10 env~

**Comment by Real-YuZhe** [comment]
Try manually putting the device into download mode and try again. To do this, keep GPIO0 low while toggling reset. On many development boards, the “Boot” button is connected to GPIO0, and you can press “Reset” button while holding “Boot”.

**Comment by BigJohnn** [comment]
> 

Thank you very much! I'll try this later～

**Comment by BigJohnn** [comment]
@Real-YuZhe It WORKS again! 多谢多谢~~
