### ISSUE TITLE
esp-box Overall interface left and right mirror image (AEGHB-386)

### ISSUE THREAD

**Issue by hyoutom** [espressif/esp-box#100]
After compiling and burning in the v0.3.0 environment, the overall interface of the esp-box example factory is mirrored on both sides. What should I do if there are any issues with the display?

**Comment by espressif2022** [comment]
You can try the new version, tag v0.5.0, 
This version the SPI speed id too high, you can set it to 40MHz

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
