### ISSUE TITLE
Install firmware V0.5.0 on ESP32-S3-BOX3 (revision v0.2) not work (AEGHB-391)

### ISSUE THREAD

**Issue by SepuWeb** [espressif/esp-box#102]
Hi,
today I received my brand new ESP32-S£-BOX-3, and works very well.
after reading the real guides, I read that it is better to update the firmware so I ended up in this guide:

https://github.com/espressif/esp-box/blob/v0.3.0/docs/firmware_update.md#firmware-update-for-macos

I downloaded the ESP-BOX_Demo_EN_V0.5.0.bin file on my Mac and launched the various commands.

![flash-0 5 0](https://github.com/espressif/esp-box/assets/3437329/0b305e23-1062-4505-8df2-eee0a3833fcb)

It does everything as directed but then the device no longer works! Black screen! I tried resetting, unplugging and reconnecting, but nothing.
Then I tried from Launchpad, I did ERASE FLASH but it gets stuck like this:

![image](https://github.com/espressif/esp-box/assets/3437329/7396b5a6-5242-4711-855b-554cdb6a0f81)

so i tried to install this:
![image](https://github.com/espressif/esp-box/assets/3437329/34f58e10-3bbd-4c42-963f-2e074aa3e8ba)

but when I do RESET DEVICE from Console appen this
![image](https://github.com/espressif/esp-box/assets/3437329/f3dd809b-fa2d-4ca2-8e64-f36f07d1767d)

in loop.

Please help!! I am a newbie!!

**Comment by espressif2022** [comment]
Got it, I'll check this firmware today.

**Comment by SepuWeb** [comment]
I just noticed this warning at the top of this page:

https://github.com/espressif/esp-box/blob/master/docs/firmware_update.md

Warning:

The firmware released in the latest Tag branch ([Version v0.5.0](https://github.com/espressif/esp-box/releases)) is only applicable to ESP32-S3-BOX and ESP32-S3-BOX-Lite. For users who have purchased ESP32-S3-BOX-3, we will release firmware updates during the project's progression. We suggest that users update the firmware via Espressif's online firmware flashing tool [ESP Launchpad](https://espressif.github.io/esp-launchpad/?flashConfigURL=https://raw.githubusercontent.com/espressif/esp-box/master/launch.toml).



so what can I do now? Isn't there a way to restore the original image?

**Comment by alibukharai** [comment]
@SepuWeb please check the firmware is already updated onto the [LaunchPad](https://espressif.github.io/esp-launchpad/?flashConfigURL=https://raw.githubusercontent.com/espressif/esp-box/master/launch.toml). Meanwhile you can also try to build the factory demo app by yourself by following the [guidelines](https://github.com/espressif/esp-box/tree/master/examples/factory_demo).

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
