### ISSUE TITLE
Word "Rader" in Sensor Monitor page of facrory_demo (AEGHB-454)

### ISSUE THREAD

**Issue by DejinChen** [espressif/esp-box#112]
Word "Rader" in Sensor Monitor page of factory_demo, does it mean "Radar"?

**Comment by LHYhorion** [comment]
> Word "Rader" in Sensor Monitor page of factory_demo, does it mean "Radar"?

Thank you for your keen observation. We have identified the issue and made immediate corrections. Subsequent firmware updates, starting with version 1.2.4, will address this issue.
