### ISSUE TITLE
Question: how can I get a manual pairing code for the esp-box matter switch example (AEGHB-473)

### ISSUE THREAD

**Issue by oidebrett** [espressif/esp-box#118]
Hi,

Can you advise on how I can get the manual pairing code for the matter switch example?

For example, when using the ESP32 examples from the matter (project chip repo) I can see the manual pairing code in the idf.py monitor logs like this

```
I (2535) chip[SVR]: SetupQRCode: [MT:Y.XXXXXXXXXXXXXXXXXXX]
I (2545) chip[SVR]: Copy/paste the below URL in a browser to see the QR Code:
I (2555) chip[SVR]: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3AY.K9042C00KA0648G00
I (2565) chip[SVR]: Manual pairing code: [3XXXXXXXXXX2]
```

When I idf.py monitor the esp-box matter switch example I cant see such a code? Is there some configuration settings that I need to set before compiling?

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
