### ISSUE TITLE
请问下esp-box的界面是用的哪个设计器?

### ISSUE THREAD

**Issue by Beanv587** [espressif/esp-box#12]
是用的官方的EdgeLine吗?

另外问下font_cmd_cn_36.c里的字体也是设计器生成的吗?能提供下字体名吗?

我这边同时购买了s3-box跟se-box-lite裸板,看了电路原理图跟s3-box对比应该是一样的屏幕接口,区别只是是否支持触屏.我把s3-box的屏幕的排线插到了Lite裸板上,为啥点亮不了屏幕呢?代码里我注释了触控驱动初始化（bsp_tp_init）

lite出厂例程有吗?生成的固件也行阿..

谢谢

**Comment by ESP-Mars** [comment]
是用的官方的EdgeLine吗?  --- 不是
另外问下font_cmd_cn_36.c里的字体也是设计器生成的吗?能提供下字体名吗? -- https://github.com/paraself/PingFang-Fonts
s3-box 和 lite 裸板屏幕不是设计成能够互换的。
lite 固件还在准备中，会尽快发布

**Comment by Beanv587** [comment]
> 

@ESP-Mars 好嘞,我再研究研究.谢谢
