### ISSUE TITLE
[Question] Does it support cam, like ESP32 Cam OV5640, or any cam ? Thank you. (AEGHB-496)

### ISSUE THREAD

**Issue by selfhostrepo** [espressif/esp-box#125]
[Question] Does it support cam, like ESP32 Cam OV5640, or any cam ? Thank you.

**Comment by espressif2022** [comment]
you can refer to the example: usb_camera_lcd_display, it's a usb camera.
[camera link](https://item.taobao.com/item.htm?ft=t&id=742819252609)

**Comment by ESP-Mars** [comment]
We also have a esp-camera repo that list all DVP camera drivers supported by ESP32 series chips, https://github.com/espressif/esp32-camera

**Comment by espressif2022** [comment]
Hello，I'll close this PR. If you have any question of esp-box, you can create a new one, thanks.
