### ISSUE TITLE
[Question] Does it support any e-ink screen? Thank you. (AEGHB-497)

### ISSUE THREAD

**Issue by selfhostrepo** [espressif/esp-box#126]
[Question] Does it support any e-ink screen? Thank you.

**Comment by espressif2022** [comment]
This project didn't support it now, it's a spi RGB screen. But some customers use our chip to driver e-ink screen.

**Comment by ESP-Mars** [comment]
A good open-source reference for ESP32 porting with e-ink screen can be found at: https://github.com/martinberlin/cale-idf; https://github.com/martinberlin/lv_port_esp32-epaper

**Comment by espressif2022** [comment]
Hello，I'll close this PR. If you have any question of esp-box, you can create a new one, thanks.
