### ISSUE TITLE
esp32-box-lite  chatgpt-demo  (AEGHB-515)

### ISSUE THREAD

**Issue by gzlwz** [espressif/esp-box#128]
show "invalid_request_error"
===============log===========
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x18e4
load:0x403c9700,len:0x4
load:0x403c9704,len:0xda4
load:0x403cc700,len:0x3084
entry 0x403c9934
I (26) boot: ESP-IDF v5.1.2-dirty 2nd stage bootloader
I (27) boot: compile time Jan 10 2024 19:27:30
I (27) boot: Multicore bootloader
I (30) boot: chip revision: v0.1
I (34) qio_mode: Enabling default flash chip QIO
I (39) boot.esp32s3: Boot SPI Speed : 80MHz
I (44) boot.esp32s3: SPI Mode       : QIO
I (49) boot.esp32s3: SPI Flash Size : 16MB
I (54) boot: Enabling RNG early entropy source...
I (59) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 ota_0            OTA app          00 10 00010000 00600000
I (100) boot:  4 uf2              factory app      00 00 00700000 00200000
I (107) boot:  5 storage          Unknown data     01 82 00900000 00200000
I (115) boot:  6 model            Unknown data     01 82 00b00000 003e8000
I (123) boot: End of partition table
I (127) esp_image: segment 0: paddr=00010020 vaddr=3c120020 size=2306c0h (2295488) map
I (483) esp_image: segment 1: paddr=002406e8 vaddr=3fc9b900 size=07198h ( 29080) load
I (489) esp_image: segment 2: paddr=00247888 vaddr=40374000 size=08790h ( 34704) load
I (496) esp_image: segment 3: paddr=00250020 vaddr=42000020 size=11b59ch (1160604) map
I (673) esp_image: segment 4: paddr=0036b5c4 vaddr=4037c790 size=0f128h ( 61736) load
I (686) esp_image: segment 5: paddr=0037a6f4 vaddr=600fe010 size=00004h (     4) load
I (696) boot: Loaded app from partition at offset 0x10000
I (697) boot: Disabling RNG early entropy source...
I (708) cpu_start: Multicore app
I (708) octal_psram: vendor id    : 0x0d (AP)
I (709) octal_psram: dev id       : 0x02 (generation 3)
I (712) octal_psram: density      : 0x03 (64 Mbit)
I (717) octal_psram: good-die     : 0x01 (Pass)
I (722) octal_psram: Latency      : 0x01 (Fixed)
I (728) octal_psram: VCC          : 0x01 (3V)
I (733) octal_psram: SRF          : 0x01 (Fast Refresh)
I (739) octal_psram: BurstType    : 0x01 (Hybrid Wrap)
I (744) octal_psram: BurstLen     : 0x01 (32 Byte)
I (750) octal_psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (756) octal_psram: DriveStrength: 0x00 (1/1)
I (762) MSPI Timing: PSRAM timing tuning index: 4
I (767) esp_psram: Found 8MB PSRAM device
I (771) esp_psram: Speed: 80MHz
I (853) mmu_psram: Instructions copied and mapped to SPIRAM
I (854) cpu_start: Pro cpu up.
I (854) cpu_start: Starting app cpu, entry point is 0x403758cc
0x403758cc: call_start_cpu1 at D:/Espressif50-ide/frameworks/esp-idf-v5.1.2/components/esp_system/port/cpu_start.c:157

I (0) cpu_start: App cpu up.
I (1101) esp_psram: SPI SRAM memory test OK
I (1110) cpu_start: Pro cpu start user code
I (1110) cpu_start: cpu freq: 240000000 Hz
I (1110) cpu_start: Application information:
I (1113) cpu_start: Project name:     chatgpt_demo
I (1118) cpu_start: App version:      v0.5.0-44-g88cca17
I (1124) cpu_start: Compile time:     Jan 10 2024 19:27:10
I (1131) cpu_start: ELF file SHA256:  7563b3c8abc0db92...
I (1137) cpu_start: ESP-IDF:          v5.1.2-dirty
I (1142) cpu_start: Min chip rev:     v0.0
I (1147) cpu_start: Max chip rev:     v0.99
I (1152) cpu_start: Chip rev:         v0.1
I (1157) heap_init: Initializing. RAM available for dynamic allocation:
I (1164) heap_init: At 3FCA8018 len 000416F8 (261 KiB): DRAM
I (1170) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (1177) heap_init: At 600FE014 len 00001FD4 (7 KiB): RTCRAM
I (1183) esp_psram: Adding pool of 7040K of PSRAM memory to heap allocator
I (1191) spi_flash: detected chip: gd
I (1195) spi_flash: flash io: qio
I (1200) sleep: Configure to isolate all GPIO pins in sleep state
I (1206) sleep: Enable automatic switching of GPIO sleep configuration
I (1213) app_start: Starting scheduler on CPU0
I (1218) app_start: Starting scheduler on CPU1
I (1218) main_task: Started on CPU0
I (1228) esp_psram: Reserving pool of 8K of internal memory for DMA/internal allocations
I (1236) main_task: Calling app_main()
I (1257) settings: stored ssid:xxxxxxxxxxxxxx
I (1257) settings: stored password:xxxxxxxxxxxxxxxxxxxxxxxx
I (1257) settings: stored OpenAI:sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
I (1264) settings: stored Base URL:https://api.chatanywhere.com.cn/v1
I (1396) ESP-BOX-LITE: Partition size: total: 1920401, used: 1072774
I (1396) LVGL: Starting LVGL task
I (1397) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (1405) gpio: GPIO[48]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (1536) button: IoT Button Version: 3.2.0
I (1537) adc button: ADC1 has been initialized
I (1537) adc button: calibration scheme version is Curve Fitting
I (1542) adc button: Calibration Success
I (1547) button: IoT Button Version: 3.2.0
I (1551) button: IoT Button Version: 3.2.0
I (1556) button: IoT Button Version: 3.2.0
I (1561) gpio: GPIO[0]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (1574) gpio: GPIO[46]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (1586) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (1587) I2S_IF: STD Mode 1 bits:16/16 channel:2 sample_rate:16000 mask:3
I (1595) Adev_Codec: Open codec device OK
I (1598) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (1604) I2S_IF: STD Mode 0 bits:16/16 channel:2 sample_rate:16000 mask:3
I (1612) Adev_Codec: Open codec device OK
W (1616) bsp_sensor: This example don't support Sensor!!
I (1622) app_main: Display LVGL demo
I (1627) ESP-BOX-LITE: Setting LCD backlight: 100%
I (1661) app_main: speech recognition start
I (1661) MODEL_LOADER: The storage free size is 22272 KB
I (1661) MODEL_LOADER: The partition size is 4000 KB
I (1664) pp: pp rom version: e7ae62f
I (1671) net80211: net80211 rom version: e7ae62f
I (1668) MODEL_LOADER: Successfully map model partition
I (1682) AFE_SR: afe interface for speech recognition

I (1688) AFE_SR: AFE version: SR_V220727

I (1693) AFE_SR: Initial auido front-end, total channel: 3, mic num: 2, ref num: 1

I (1701) AFE_SR: aec_init: 0, se_init: 1, vad_init: 1

I (1707) AFE_SR: wakenet_init: 1

I (1677) wifi:wifi driver task: 3fcbf204, prio:23, stack:6656, core=0
I (1725) wifi:wifi firmware version: 91b9630
I (1726) wifi:wifi certification version: v7.0
I (1726) wifi:config NVS flash: enabled
I (1729) wifi:config nano formating: disabled
I (1733) wifi:Init data frame dynamic rx buffer num: 32
I (1738) wifi:Init static rx mgmt buffer num: 5
I (1742) wifi:Init management short buffer num: 32
I (1747) wifi:Init static tx buffer num: 16
I (1751) wifi:Init tx cache buffer num: 32
I (1754) wifi:Init static tx FG buffer num: 2
I (1759) wifi:Init static rx buffer size: 1600
I (1763) wifi:Init static rx buffer num: 16
I (1767) wifi:Init dynamic rx buffer num: 32
I (1773) wifi_init: rx ba win: 16
I (1775) wifi_init: tcpip mbox: 32
I (1779) wifi_init: udp mbox: 6
I (1783) wifi_init: tcp mbox: 6
I (1787) wifi_init: tcp tx win: 5744
I (1791) wifi_init: tcp rx win: 5744
I (1795) wifi_init: tcp mss: 1440
I (1799) wifi_init: WiFi/LWIP prefer SPIRAM
I (1805) wifi_init: WiFi IRAM OP enabled
I (1809) wifi_init: WiFi RX IRAM OP enabled
I (1815) phy_init: phy_version 620,ec7ec30,Sep  5 2023,13:49:13
I (1854) wifi:mode : sta (7c:df:a1:e1:c6:04)
I (1855) wifi:enable tsf
I (1856) wifi station: start connect to the AP
I (1856) wifi station: wifi_init_sta finished.RT3000, shenyuli0402
I (1862) wifi station: NET_EVENT_POWERON_SCAN
MC Quantized wakenet9: wakenet9_v1h12_nihaoxiaozhi_3_0.585_0.595, tigger:v3, mode:2, p:0, (Jul  7 2023 11:10:53)
I (1971) AFE_SR: wake num: 3, mode: 0, (Jul  7 2023 11:10:53)

I (1971) app_sr: Set language EN
I (1971) app_sr: load wakenet:wn9_nihaoxiaozhi
MC Quantized wakenet9: wakenet9_v1h12_nihaoxiaozhi_3_0.585_0.595, tigger:v3, mode:2, p:0, (Jul  7 2023 11:10:53)
I (2009) AFE_SR: wakenet wn_frame_size = 512

I (2013) app_sr: Feed Task
I (2016) app_sr: audio_chunksize=1024, feed_channel=3
I (2022) app_sr: Detection task
successfully created record_audio_buffer with a size: 256000
audio_rx_buffer with a size: 1048576
I (2212) file_iterator: File : echo_cn_end.wav
I (2225) file_iterator: File : echo_cn_ok.wav
I (2231) file_iterator: File : echo_cn_wake.wav
I (2237) file_iterator: File : echo_en_end.wav
I (2250) file_iterator: File : echo_en_ok.wav
I (2258) file_iterator: File : echo_en_wake.wav
I (2260) file_iterator: File : Hi.mp3
I (2269) file_iterator: File : Hi.wav
I (2287) file_iterator: File : input.wav
I (2288) file_iterator: File : tts_failed.mp3
I (2291) file_iterator: File : waitPlease.mp3
W (2326) app_sr: AFE Fetch Fail
W (2626) app_sr: AFE Fetch Fail
W (2926) app_sr: AFE Fetch Fail
W (3226) app_sr: AFE Fetch Fail
W (3526) app_sr: AFE Fetch Fail
W (3826) app_sr: AFE Fetch Fail
W (4126) app_sr: AFE Fetch Fail
I (4287) wifi station: Total APs scanned = 6, ret:0
I (4287) wifi station: SSID             RT3000
I (4287) wifi station: SSID             TP-LINK_5A49
I (4291) wifi station: SSID             TP-LINK_9799
I (4295) wifi station: SSID             CMCC-S4gb
I (4300) wifi station: SSID             Redmi_4C87
I (4304) wifi station: SSID             baihe-701
I (4315) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (4316) wifi:state: init -> auth (b0)
I (4348) wifi:state: auth -> assoc (0)
I (4361) wifi:state: assoc -> run (10)
I (4383) wifi:connected with RT3000, aid = 9, channel 1, BW20, bssid = 10:9f:4f:c3:a1:35
I (4384) wifi:security: WPA2-PSK, phy: bgn, rssi: -53
I (4387) wifi:pm start, type: 1

I (4388) wifi:set rx beacon pti, rx_bcn_pti: 0, bcn_timeout: 25000, mt_pti: 0, mt_time: 10000
I (4401) wifi:<ba-add>idx:0 (ifx:0, 10:9f:4f:c3:a1:35), tid:0, ssn:0, winSize:64
W (4426) app_sr: AFE Fetch Fail
I (4474) wifi:AP's beacon interval = 102400 us, DTIM period = 1
W (4726) app_sr: AFE Fetch Fail
W (5026) app_sr: AFE Fetch Fail
W (5326) app_sr: AFE Fetch Fail
W (5626) app_sr: AFE Fetch Fail
I (5897) esp_netif_handlers: sta ip: 192.168.10.9, mask: 255.255.255.0, gw: 192.168.10.1
I (5898) wifi station: got ip:192.168.10.9
I (16436) app_sr: wakeword detected
I (16436) app_audio: ### record Start
I (16436) ui_ctrl: act_scr:0x3fcb55b4, ui_ScreenSetup:0x3fcb55b4
I (16441) ui_ctrl: Swich to panel[1]
I (16516) app_audio: frame_rate= 16000, ch=2, width=16
I (16518) I2S_IF: Pending out channel for in channel running
E (16527) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (16528) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (16532) I2S_IF: STD Mode 1 bits:16/16 channel:2 sample_rate:16000 mask:3
I (16560) Adev_Codec: Open codec device OK
E (16560) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (16563) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (16568) I2S_IF: STD Mode 0 bits:16/16 channel:2 sample_rate:16000 mask:3
I (16573) app_sr: AFE_FETCH_CHANNEL_VERIFIED, channel index: 2

I (16578) Adev_Codec: Open codec device OK
I (24268) app_audio: ESP_MN_STATE_TIMEOUT
I (24268) app_audio: ### record Stop, 125829 122K
I (24303) OpenAI: OpenAI create, version: 0.3.1
I (24303) ui_ctrl: Swich to panel[2]
I (24304) app_audio: Player PLAYING
I (24322) I2S_IF: Pending out channel for in channel running
E (24337) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (24337) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (24341) I2S_IF: STD Mode 1 bits:16/16 channel:2 sample_rate:16000 mask:3
I (24349) wifi:<ba-add>idx:1 (ifx:0, 10:9f:4f:c3:a1:35), tid:5, ssn:0, winSize:64
I (24382) Adev_Codec: Open codec device OK
E (24382) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (24384) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (24391) I2S_IF: STD Mode 0 bits:16/16 channel:2 sample_rate:16000 mask:3
I (24422) Adev_Codec: Open codec device OK
I (24458) esp-x509-crt-bundle: Certificate validated

E (25088) esp-tls-mbedtls: write error :-0x0050:
E (25088) transport_base: esp_tls_conn_write error, errno=Connection reset by peer
E (25090) OpenAI: ./managed_components/espressif__openai/OpenAI.c:2393 (OpenAI_Request):Failed to write client!
E (25102) OpenAI: ./managed_components/espressif__openai/OpenAI.c:2080 (OpenAI_AudioTranscriptionFile):Empty result!

I (25113) ui_ctrl: update listen speak

E (25117) app_main: start_openai(85): [audioTranscription]: invalid url

I (27873) app_audio: Player IDLE
I (27876) I2S_IF: Pending out channel for in channel running

E (27884) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet

I (27884) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (27888) I2S_IF: STD Mode 1 bits:16/16 channel:2 sample_rate:16000 mask:3
I (27915) Adev_Codec: Open codec device OK

E (27915) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet

I (27917) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (27924) I2S_IF: STD Mode 0 bits:16/16 channel:2 sample_rate:16000 mask:3
I (27939) Adev_Codec: Open codec device OK
I (27939) app_main: replay audio end
=====================================
api key and base url has pass through chatbox and  esp32 Audio

but can't run in this case.

**Comment by espressif2022** [comment]
can you try this url with `curl` ? I tried it, and the result is  `401 Authorization Required`

```
request:
curl https://api.chatanywhere.com.cn/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer  $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
result:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>401 Authorization Required</title></head>
<body>
<h1>401 Authorization Required</h1>
<p>This server could not verify that you are authorized to access the document requested.<hr/>Powered by Tengine</body>
</html>
```

```
request:
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer  $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
result:
{
  "id": "chatcmpl-8fetdWnNxgrsXs5JknHW5W4SZLNUh",
  "object": "chat.completion",
  "created": 1704939345,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! How may I assist you today?"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 19,
    "completion_tokens": 9,
    "total_tokens": 28
  },
  "system_fingerprint": null
}
```

**Comment by gzlwz** [comment]
It is not opai api key 
the url & api key come from the next link:
https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file

免费版支持gpt-3.5-turbo, embedding, gpt-4。其中gpt-4由于价格过高，每24小时限制10次调用，且不支持流式传输。需要更稳定快速的gpt-4请使用付费版。
转发Host1: https://api.chatanywhere.tech (国内中转，延时更低，host1和host2二选一)
转发Host2: https://api.chatanywhere.com.cn (国内中转，延时更低，host1和host2二选一)
转发Host3: https://api.chatanywhere.cn (国外使用,国内需要全局代理)
[Issues](https://github.com/chatanywhere/GPT_API_free/issues)
该API Key用于转发API，需要将Host改为api.chatanywhere.tech(国内首选)或者api.chatanywhere.cn(国外使用，国内需要全局代理)。

**Comment by gzlwz** [comment]
Because we can't direct access the openai in mainland.

**Comment by gzlwz** [comment]
I (473880) I2S_IF: Pending out channel for in channel running
E (473892) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (473892) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (473896) I2S_IF: STD Mode 1 bits:16/16 channel:2 sample_rate:16000 mask:3
I (473930) Adev_Codec: Open codec device OK


E (473930) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet


I (473932) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (473939) I2S_IF: STD Mode 0 bits:16/16 channel:2 sample_rate:16000 mask:3
I (473965) Adev_Codec: Open codec device OK
I (473983) esp-x509-crt-bundle: Certificate validated
I (476177) ui_ctrl: update listen speak


E (476178) app_main: start_openai(85): [audioTranscription]: invalid url


I (477400) app_audio: Player IDLE
I (477402) I2S_IF: Pending out channel for in channel running
E (477417) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (477417) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (477421) I2S_IF: STD Mode 1 bits:16/16 channel:2 sample_rate:16000 mask:3
I (477449) Adev_Codec: Open codec device OK
E (477449) i2s_common: i2s_channel_disable(1030): the channel has not been enabled yet
I (477451) I2S_IF: channel mode 0 bits:16/16 channel:2 mask:3
I (477459) I2S_IF: STD Mode 0 bits:16/16 channel:2 sample_rate:16000 mask:3
I (477470) Adev_Codec: Open codec device OK
I (477471) app_main: replay audio end

**Comment by espressif2022** [comment]
> Because we can't direct access the openai in mainland.

I know this, so you need to make sure that the proxy server is accessible on the PC first, I tested it locally, and your url curl commands are inaccessible.
It's definitely not accessible on the device.

**Comment by gzlwz** [comment]
yeah,　Ｉ　ｈａｄ　ａｌｒｅａｄｙ　．

curl https://api.chatanywhere.com.cn/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer $OPENAI_API_KEY" \
>   -d '{
>     "model": "gpt-3.5-turbo",
>     "messages": [
>       {
>         "role": "system",
>         "content": "You are a helpful assistant."
>       },
>       {
>         "role": "user",
>         "content": "Hello!"
>       }
>     ]
>   }'
{"id":"chatcmpl-8gEDp3nAMzqGh05Lh15SokKAb2s7e",
"object":"chat.completion",
"created":1705075137,
"model":"gpt-3.5-turbo-1106",
"choices":[
{"index":0,"
message":{"role":"assistant","content":"Hello! How can I assist you today?"},
"logprobs":nu

**Comment by dujianmin** [comment]
E (22066) HTTP_CLIENT: Error parse url audio/transcriptions
E (22071) HTTP_CLIENT: Failed to set URL

**Comment by LHYhorion** [comment]
> yeah,　Ｉ　ｈａｄ　ａｌｒｅａｄｙ　．
> 
> curl https://api.chatanywhere.com.cn/v1/chat/completions \
> 
> > -H "Content-Type: application/json" 
> > -H "Authorization: Bearer $OPENAI_API_KEY" 
> > -d '{
> > "model": "gpt-3.5-turbo",
> > "messages": [
> > {
> > "role": "system",
> > "content": "You are a helpful assistant."
> > },
> > {
> > "role": "user",
> > "content": "Hello!"
> > }
> > ]
> > }'
> > {"id":"chatcmpl-8gEDp3nAMzqGh05Lh15SokKAb2s7e",
> > "object":"chat.completion",
> > "created":1705075137,
> > "model":"gpt-3.5-turbo-1106",
> > "choices":[
> > {"index":0,"
> > message":{"role":"assistant","content":"Hello! How can I assist you today?"},
> > "logprobs":nu

I tried your URL, and it showed a 401 error message

**Comment by LHYhorion** [comment]
> yeah,　Ｉ　ｈａｄ　ａｌｒｅａｄｙ　．
> 
> curl https://api.chatanywhere.com.cn/v1/chat/completions \
> 
> > -H "Content-Type: application/json" 
> > -H "Authorization: Bearer $OPENAI_API_KEY" 
> > -d '{
> > "model": "gpt-3.5-turbo",
> > "messages": [
> > {
> > "role": "system",
> > "content": "You are a helpful assistant."
> > },
> > {
> > "role": "user",
> > "content": "Hello!"
> > }
> > ]
> > }'
> > {"id":"chatcmpl-8gEDp3nAMzqGh05Lh15SokKAb2s7e",
> > "object":"chat.completion",
> > "created":1705075137,
> > "model":"gpt-3.5-turbo-1106",
> > "choices":[
> > {"index":0,"
> > message":{"role":"assistant","content":"Hello! How can I assist you today?"},
> > "logprobs":nu

Hello, I tested your URL and received a 401 warning. I suggest you try using a different URL for testing.

**Comment by LHYhorion** [comment]
Perhaps you can try using the URL https://api.xiaoyukefu.com/v1/. It has been tested and is functional.

**Comment by gzlwz** [comment]
无法访问此网站网址为 https://api.xiaoyukefu.com/v1/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by LHYhorion** [comment]
You need to add this URL to CONFIG.INI or configure it in menuconfig. You cannot directly open and use https://api.xiaoyukefu.com/v1/.

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
