### ISSUE TITLE
ESP32-S3-BOX-3 USB串口通信问题 (AEGHB-517)

### ISSUE THREAD

**Issue by ME-KevinHan** [espressif/esp-box#129]
_背景：我使用VSCode的ESP-IDF组件开发，在该开发板上搭建提供的例程的时候，选择了目标开发板box3，但是仍然会下载lite和box的文件，并导致重定义问题。将dependencies.lock和managed_components中的lite和box相关文件删除之后再次搭建可以成功，并且烧录也成功。在使用factory demo和image display例程的时候USB串口接入电脑也可以识别。_

**目前的问题是**：在烧录完成 usb_camera_lcd_display例程之后，接入免驱USB摄像头，可以显示图像。然而目前开发板使用USB接入电脑后可以成功开机，但是电脑无法识别端口。

请问这可能是什么原因呢，我应该如何在USB无法使用的情况下重新刷入出厂固件程序呢？

**Comment by ESP-Mars** [comment]
如遇 USB 下载失败，请按住 Boot 按键的同时按一下 Reset 按键手动进入“固件下载”模式。
