### ISSUE TITLE
怎么样将esp-adf集成到ESP-BOX的工程中？

### ISSUE THREAD

**Issue by MinjunHuang** [espressif/esp-box#13]
我在esp-box中创建我自己的项目，但我想在我的esp-box应用中集成esp-adf框架，以使用esp-adf的语音播放器功能，是否可行？有没有相关指南或者例子？

**Comment by ESP-Mars** [comment]
adf 暂时不支持

**Comment by Beanv587** [comment]
> 可行，但是 esp-box 没有计划集成 esp-adf，可能后续 adf 会支持 box 开发板。

@ESP-Mars 目前adf不是已经更新支持了box、box-lite了嘛.我都跑过N个例程了,能用.虽然部分带sd卡的例程跑不了,小改一下就行.问题不大的

**Comment by MinjunHuang** [comment]
是的，我也看到adf有对box的支持le,多谢。
