### ISSUE TITLE
Feb 2024, cannot buy one anywhere, when will you have them? (AEGHB-559)

### ISSUE THREAD

**Issue by dac2020** [espressif/esp-box#131]
I was going to order one from Amazon but it shows nothing available until April. I looked all over and see no stick anywhere. 
When will these be available for sale again?

**Comment by ESP-Mars** [comment]
If you don't need many accessories, you can purchase the [ESP32-S3-BOX-3B](https://www.amazon.com/Espressif-ESP32-S3-BOX-3B-Development-Board/dp/B0CSJC5BX6/ref=sr_1_1?crid=3E9INZGU82PSO&dib=eyJ2IjoiMSJ9.a_tBpTdNBu4KhZ2SPdlEMhAZOJ9isPbL9wC3OTFVJCrRWoYPrJ4EMreKFIo5GMUP1usnBHOmaZd_RruBOQXFhbh2ekSEvF8pdyrH56V3JyhowcOl1bX3_yTnROW6XcqA9eu8-Vekhe-198E363FtZt3qO-Jb9FX3QimRcIsV7vOg6zXnOCFPaJL0UxccYqePYAi8bjcbSAyw-Crrum1jR5OXBW-PXzVLU7uOb-KYUws.ByTcTETB6QkIEnXqIQtxakhrw6HtfV9AG0WyS184u2Y&dib_tag=se&keywords=ESP32-S3-BOX-3B%2BDevelopment%2BBoard&qid=1708570377&sprefix=%2Caps%2C459&sr=8-1&th=1) as an alternative. The ESP32-S3-BOX-3 comes in two different versions: ESP32-S3-BOX-3 and ESP32-S3-BOX-3B. The ESP32-S3-BOX-3 represents the standard edition, equipped with four blue accessories, while the ESP32-S3-BOX-3B provides fewer accessories to meet the needs of beginners who don't require too much unnecessary hardware. Here are the distinctions between the two versions:
![Comparison](https://github.com/espressif/esp-box/assets/85924095/7206b842-7960-43fc-88ae-ce9cc816cccc)


Please click [here](https://www.espressif.com/en/products/devkits), scroll down, and go to ESP32-S3-BOX-3 to explore all available purchase channels.

**Comment by dac2020** [comment]
I want an ESP32 WiFi display that can receive and display messages from MQTT. 
However, it's not clear if I need the bracket or not for this basic function.

**Comment by ESP-Mars** [comment]
@dac2020 Considering the requirements you've described, the ESP32-S3-BOX-3B should be sufficient. Could you please specify your country? We can assist you in finding the appropriate purchasing channels.

**Comment by dac2020** [comment]
USA, typically order from Amazon.

**Comment by ESP-Mars** [comment]
@dac2020 We apologize for the insufficient availability of the product. We are actively expediting production. Please keep an eye on platforms such as AliExpress, Mouser, and Adafruit for updates.

**Comment by 1544k** [comment]
Not sure if I just got particularly lucky, although  higher lead time was indicated, had my backorder on digikey fullfilled within a month, got it last week shipped within two days to Germany.

**Comment by dac2020** [comment]
Personally, I only purchase from Amazon because it's very fast delivery and returns if there are problems. 
Buying overseas takes much longer and returning an item not working is much harder and longer.

**Comment by ESP-Mars** [comment]
The BOX-3 is in urgent production, and a batch of goods will be available on AliExpress and Amazon next week.

**Comment by raminf** [comment]
I am also looking for the BOX-3. Specifically need one with the microphone and a speaker for a voice recognition application. 

It's not clear from the table above if the 3B has those or not. I went ahead and ordered a 3B on AliExpress, just in case. Will the 3B be enough or should I wait for the BOX-3? Thanks!

**Comment by ESP-Mars** [comment]
@raminf If you specifically need one with a microphone and speaker, the BOX-3B is sufficient, as the BOX-3 only has some additional sensor accessories and adapter boards compared to the BOX-3B.

**Comment by ESP-Mars** [comment]
> USA, typically order from Amazon.

@dac2020 Arrival on Amazon: https://www.amazon.com/dp/B0CL6HD8JX?ref=myi_title_dp&th=1

**Comment by touchgadget** [comment]
@ESP-Mars All sold?
![amazon](https://github.com/espressif/esp-box/assets/65133219/2ded16ec-9aba-480b-a89a-e550b651de92)

**Comment by ESP-Mars** [comment]
@touchgadget  My Amazon shows that there is stock available for delivery to "Deliver to Houston 77022.
<img width="1327" alt="Screenshot 2024-04-22 at 10 26 31" src="https://github.com/espressif/esp-box/assets/85924095/4354c086-a099-4fad-a548-3439fdea3888">

**Comment by touchgadget** [comment]
@ESP-Mars 
Thanks, I see the boards are available now!

**Comment by ESP-Mars** [comment]
Temporarily closed the issue. Should you have additional questions or concerns, don't hesitate to reopen the issue.
