### ISSUE TITLE
atgpt demo获取chatgpt结果后，一直没有tts语音合成播放，一直返回：E (580156) audio: unknown file type, cleaning up (AEGHB-599)

### ISSUE THREAD

**Issue by shantai57** [espressif/esp-box#138]
查看openai官方文档默认返回**MP3**格式音频，但是接收回来的数据一直解析不出来是什么格式。
![PixPin_2024-03-26_09-39-32](https://github.com/espressif/esp-box/assets/93563246/8c218d78-e90b-4e7b-9b48-99fa556e2dc0)
将音频数据保存到文件，然后打开文件进行播放也是报一样的错误：**E (580156) audio: unknown file type, cleaning up**
![PixPin_2024-03-26_09-47-52](https://github.com/espressif/esp-box/assets/93563246/6b497d96-4feb-4a46-9bf2-6e86ba69d2d6)
请问上述问题怎么解决，谢谢！

**Comment by espressif2022** [comment]
可以使用在线命令，先获取下音频文件，导到板子和本地分别看下？
```
curl https://api.openai.com/v1/audio/speech \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "tts-1",
    "input": "Today is a wonderful day to build something people love!",
    "voice": "alloy"
  }' \
  --output speech.mp3
```

**Comment by shantai57** [comment]
可以的，都能播放出来。

![Uploading PixPin_2024-03-26_11-15-35.png…]()

**Comment by shantai57** [comment]
可以的，PC和板子都能播放出来。

![PixPin_2024-03-26_11-15-35](https://github.com/espressif/esp-box/assets/93563246/f223fe4b-021d-4f68-9a71-a16e64d4016e)

**Comment by shantai57** [comment]
正常导入的音频和预置的音频播放都没问题，就是通过源码从openai获取的音频解析不成功。

**Comment by espressif2022** [comment]
> 正常导入的音频和预置的音频播放都没问题，就是通过源码从openai获取的音频解析不成功。

之前在 audio 结尾会出问题，curl 获取的，和本地获取的现象一致，现已修复；
头上直接出错的，且只有这边 TTS 拿到的出问题，没遇到，晚点测试下。

**Comment by shantai57** [comment]
> > 正常导入的音频和预置的音频播放都没问题，就是通过源码从openai获取的音频解析不成功。
> 
> 之前在 audio 结尾会出问题，curl 获取的，和本地获取的现象一致，现已修复； 头上直接出错的，且只有这边 TTS 拿到的出问题，没遇到，晚点测试下。

好的，谢谢

**Comment by LHYhorion** [comment]
请问您的网络环境是怎样的？如果是在国内的话，可能直接访问 OpenAI 会有问题，您可以尝试更换 URL 为：https://api.xiaoyukefu.com/v1/
并再次测试是否有同样问题出现？我刚刚进行了测试没有出现与您相似的情况。
