### ISSUE TITLE
4g模组 (AEGHB-274)

### ISSUE THREAD

**Issue by banshow** [espressif/esp-box#14]
是否支持4g模组？怎么连接？

**Comment by leeebo** [comment]
ESP32-S3 可以通过 USB 连接一个 4G Cat.1 模组上网，或通过 AP 模式给其它设备上网，示例程序：https://github.com/espressif/esp-iot-solution/tree/usb/add_usb_solutions/examples/usb/host/usb_cdc_4g_module

所以 ESP-BOX 也能支持

但是硬件上要注意的是 BOX 的 Type-C 接口只能输入 5V，不能输出 5V，所以需要给 4G 模块单独供电

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!
