### ISSUE TITLE
gpt_demo运行时的录音时长问题 (AEGHB-613)

### ISSUE THREAD

**Issue by welkinchan** [espressif/esp-box#140]
运行GPT_DEMO的时候，发现在唤醒词之后的语音输入阶段，
如果语音在5s左右，通常都能正常工作。
但有时候还没说完，比如10-15s左右，有时候录音会提前自行结束，
也有时候会等说完话后结束录音，感觉有点不稳定。
我的IDF是5.1版本，esp-box是mater版本。

**Comment by welkinchan** [comment]
发现是距离稍远时，VAD被判定中止了。距离近一点就没有这个问题。

**Comment by LHYhorion** [comment]
也许是由于远距离和低音量的环境，导致 I2S 在某些时段未能有效获取数据，因而被认为传输结束。我已进行了同样的测试，并未发现类似情况，建议您可以进行更多测试以确认。
