### ISSUE TITLE
esp-box的代码能否运行在korvo的板子上？ (AEGHB-633)

### ISSUE THREAD

**Issue by welkinchan** [espressif/esp-box#142]
我想把esp-box里的例子，主要是gpt_demo放在korvo_v2的板子上运行。
但是看了下，menuconfig里边并没有korvo_v2的配置。
所以想咨询下，如果想放在korvo_v2的板子上运行的话，我应该怎么实现呢？
请问是否方便告知下主要的思路，以及代码主要需要变更的地方？

**Comment by Horion0415** [comment]
您好，目前不能直接在 korvo_v2 上跑，但是您可以移植 korvo 的 bsp。同时您还需要注意 korvo 的硬件没有 ESP-BOX 丰富，因此部分功能不能实现，

**Comment by welkinchan** [comment]
> 您好，目前不能直接在 korvo_v2 上跑，但是您可以移植 korvo 的 bsp。同时您还需要注意 korvo 的硬件没有 ESP-BOX 丰富，因此部分功能不能实现，

我主要是想让gpt_demo这个例程运行到korvo的板子上，我看了下两款板子，音频部分的主要器件都是一样的，所以对我来说硬件功能是足够了。
我看到在component registry里边有一个korvo_v2的组件，并且我在移植的gpt_demo的代码里边，把所有跟ui以及ltd相关的代码都注释掉了，但是编译的时候依然有很多报错。
所以，有一些引脚虽然我不用，但是直接注释掉又会导致无法编译。

这几天试了下，发现移植的难度比我预期的要大很多，请问有没有什么文件可以提供参考？

**Comment by Horion0415** [comment]
移植 BSP 的难度应该不会太大。您可以参考 korvo_v2 的例程同时比较 ESP-BOX 的例程作为移植参考。

**Comment by welkinchan** [comment]
> 移植 BSP 的难度应该不会太大。您可以参考 korvo_v2 的例程同时比较 ESP-BOX 的例程作为移植参考。

非常感谢，已经解决了！

**Comment by Kirinni** [comment]
> > 移植 BSP 的难度应该不会太大。您可以参考 korvo_v2 的例程同时比较 ESP-BOX 的例程作为移植参考。
> 
> 非常感谢，已经解决了！
>
嗨~朋友！非常高兴看到您解决了这个问题，目前我也遇到了这样的问题。我在ESP-IDF方面是个新手，对于移植开发板bsp的方法还不太清楚，能够请问一下您对哪些文件做了修改以及在何处新增了文件用于移植BSP吗？
