### ISSUE TITLE
ESP32-S3-BOX 的 LCD 屏如何购买 (AEGHB-649)

### ISSUE THREAD

**Issue by kyo-tom** [espressif/esp-box#144]
README.md 中提供了 ESP32-S3-BOX-Lite 的 LCD 屏幕购买途径，请问下 ESP32-S3-BOX 的 LCD 屏如何购买？

**Comment by espressif2022** [comment]
抱歉 ESP32-S3-BOX 的屏幕，我们这不公开单独售卖

**Comment by kyo-tom** [comment]
我看咱们现在已经开源了 ESP32-S3-BOX 的 PCB，所以我想看下能不能复刻，那如果没有屏幕的话，仅通过语音能使用吗？

**Comment by espressif2022** [comment]
> 我看咱们现在已经开源了 ESP32-S3-BOX 的 PCB，所以我想看下能不能复刻，那如果没有屏幕的话，仅通过语音能使用吗？

可以，有一些不需要触摸交互的 demo 可以使用， BSP 那需要把 TP 初始化屏蔽，不然可能会 crash。

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
