### ISSUE TITLE
example编译报错 (AEGHB-653)

### ISSUE THREAD

**Issue by nuomin0708** [espressif/esp-box#146]
在编译esp32-s3-box  v0.5.0版本的examples下的factory_demo报错，报错如下
![image](https://github.com/espressif/esp-box/assets/93308268/4c625cd6-9eb0-442d-afe1-bb58a59550d4)
像是组件版本不兼容，可是我没修改官方的代码，有什么方法解决吗？

**Comment by espressif2022** [comment]
拉一下最新的 master 试下，部分组件可能更新了导致不匹配

**Comment by nuomin0708** [comment]
> 拉一下最新的 master 试下，部分组件可能更新了导致不匹配

拉的就是最新的0.5.0版本，刚刚又试了下还是不行。

**Comment by Horion0415** [comment]
您这边可以试下拉取 master 分支，编译试下。稍后我们会测试 0.5.0 是否可以正常使用

**Comment by opsnull** [comment]
@nuomin0708 我看你用的是最近发布的 esp-idf-5.2.1 版本，可能与 esp-box 0.5.0 不兼容的, esp-box master 分支最近有几个 commit 来修复了与 esp-idf-5.2 兼容的问题，比如这个 
[example(chatgpt): fix build with idf 5.2](https://github.com/espressif/esp-box/commit/24219f7100722d62d9acd7956c44c90063bb1ec5) ，我试了下用  esp-idf-5.2.1 和 esp-box master 分支是可以正常编译的。

**Comment by nuomin0708** [comment]
> 您这边可以试下拉取 master 分支，编译试下。稍后我们会测试 0.5.0 是否可以正常使用
n抱歉，我说的0.5.0可能就是master分支。
<img width="233" alt="7ce7f05bed820a0290cf5a6c34c021a" src="https://github.com/espressif/esp-box/assets/93308268/6e9ad879-e801-412f-b752-5b8a97870dd3">

**Comment by nuomin0708** [comment]
> 我看你用的是最近发布的 esp-idf-5.2.1 版本，可能与 esp-box 0.5.0 不兼容的， esp-box master 分支最近有几个 commit 来修复了与 esp-idf-5.2 兼容的问题，比如这个 [example（chatgpt）： fix build with idf 5.2](https://github.com/espressif/esp-box/commit/24219f7100722d62d9acd7956c44c90063bb1ec5) ，我试了下用 esp-idf-5.2.1 和 esp-box master 分支是可以正常编译的。

谢谢你的回复，我用的是5.2.1的，chatgpt_demo我可以正常编译。是factory_demo不可以编译成功。

**Comment by espressif2022** [comment]
This issue is related to #154

**Comment by ESP-Mars** [comment]
Is there any progress on this issue?

**Comment by nuomin0708** [comment]
> Is there any progress on this issue?
我升级了idf manager的版本，解决了这个问题

**Comment by Quantriple** [comment]
最新的5.3.1版本，我编译了三四个例子 都没过去，包括 factory   image    mp3 这些例子
