### ISSUE TITLE
ChatGPT demo issue (AEGHB-660)

### ISSUE THREAD

**Issue by Indastri** [espressif/esp-box#147]
Hello,

I was unable to build demo on ESP32-S3-BOX-3 because the espressif/OpenAI was updated to v1.0.0 https://components.espressif.com/components/espressif/openai which introduced: Changed C++ reserved keyword 'delete' to 'deleteResponse'

with version 0.3.1 works just fine, please update the dependencies (examples/chatgpt_demo/main/idf_component.yml)
```
espressif/openai: ">=0.3.1"
```
 to
```
 espressif/openai: "0.3.1"
```
 or update the example.

Thanks,
Ondřej

**Comment by espressif2022** [comment]
Hello, we are preparing a new MR which will be released soon.

**Comment by leeebo** [comment]
fixed in 446fd125d9fb3503ad2f5f6d422fe87b906f0aae
