### ISSUE TITLE
esp s3 box cant be seen on windows machine (AEGHB-666)

### ISSUE THREAD

**Issue by waitsmd41** [espressif/esp-box#148]
The s3 box was able to be seen just a few hours ago. after trying to run chatgpt demo i couldnt see the folder for esp box. it finally showed up and i changed the config.ini file with ssd and password and api key for chatgpt. 

it was flashing saying it was connecting to network. then it would flash black back and forth. 
![IMG_6843](https://github.com/espressif/esp-box/assets/170902354/6578847e-e874-4e26-bda5-0c059dde3887)

i tried to reflash it with launch pad but now it wont even see the device. 
![Screenshot 2024-05-26 211154](https://github.com/espressif/esp-box/assets/170902354/86061350-2c60-4b75-92f4-f30f7b266247)
and windows doesnt even see it. 
![Screenshot 2024-05-26 2113362](https://github.com/espressif/esp-box/assets/170902354/e8159d44-c442-44f9-96d0-c8260864754e)

someone please help 

is this box dead?

**Comment by ESP-Mars** [comment]
If the downloading through USB fails, please hold down the Boot button and then press the Reset button to initiate Firmware Download mode manually.

**Comment by ESP-Mars** [comment]
Is there any progress on this issue?

**Comment by waitsmd41** [comment]
I gave up sometime ago.  Guess this hobby is by of my ability.  Sent from my iPhoneOn Jul 1, 2024, at 11:33 PM, Cao Yan ***@***.***> wrote:﻿
Is there any progress on this issue?

**Comment by ESP-Mars** [comment]
Temporarily closed the issue. Should you have additional questions or concerns, don't hesitate to reopen the issue.
