### ISSUE TITLE
用ESP BOX APP扫码连接设备 (AEGHB-668)

### ISSUE THREAD

**Issue by NanaZhang4524** [espressif/esp-box#149]
当在install app扫码下载完ESP BOX app之后邮箱注册后
进入添加设备时通过扫描ESP32-s3的network中的二维码在app上不能找到设备

![image](https://github.com/espressif/esp-box/assets/171147867/1bb22db3-2f54-4ac7-bab8-4af9615bd145)
![image](https://github.com/espressif/esp-box/assets/171147867/38013899-5b9e-4f43-b1cd-e0a72a6b4fc7)
请问这个怎么解决谢谢

**Comment by ESP-Mars** [comment]
配网需要打开蓝牙
如果蓝牙已打开，尝试一下蓝牙关闭 设备重启，再试一下。

**Comment by ESP-Mars** [comment]
Is there any progress on this issue?

**Comment by NanaZhang4524** [comment]
> 在这个问题上有什么进展吗？

we change the application and it successed.
