### ISSUE TITLE
chatgpt_demo stuck at Steps screen even after restart and CONFIG.ini updated (AEGHB-699)

### ISSUE THREAD

**Issue by vinny-888** [espressif/esp-box#153]
I installed the chatgpt_demo from here (https://espressif.github.io/esp-launchpad/?flashConfigURL=https://espressif.github.io/esp-box/launchpad.toml) and everything worked perfectly

I checked out the latest code and compiled and was able to flash the code from the chatgpt_demo example onto my ESP32_S3_BOX_3

When the app starts up I get the "Steps" screen and even after I set the CONFIG.ini settings and click restart, I end up back at the Steps screen and cannot get passed it.

Not sure if there is a known but or how I might be able to bypass this as I have set these settings also in the sdkconfig

```
CONFIG_ESP_WIFI_SSID="xxx"
CONFIG_ESP_WIFI_PASSWORD="xxx"
CONFIG_OPENAI_API_KEY="sk-xxx"
CONFIG_OPENAI_URL="https://api.openai.com/v1/"
```

Any help or tips on how to bypass this screen would be great

**Comment by Horion0415** [comment]
Did you follow the compilation requirements in the README for the build? The compilation process for this example is different from other examples.
