### ISSUE TITLE
BOX3无法运行 idf.py -p COM10  flash 命令，我长按boot然后按下rst 然后松开boot，在运行命令，但是没效果 (AEGHB-923)

### ISSUE THREAD

**Issue by PoohWoah** [espressif/esp-box#171]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

如题所示

**Comment by espressif2022** [comment]
COM 口和实际是否一致？去掉 -p COM10 可以么？

**Comment by PoohWoah** [comment]
> COM 口和实际是否一致？去掉 -p COM10 可以么？

感谢回复，此方式已解决。硬件我重新焊接了，可以关闭此问题链接。
