### ISSUE TITLE
我应该使用哪一个bsp？

### ISSUE THREAD

**Issue by bronya5th** [espressif/esp-box#20]
esp-s3-box分别在esp-box仓库与esp-skainet仓库各有一个bsp，区别在于esp_board_init文件，部分函数名也有细微区别，例如esp_audio_play()与bsp_audio_play()，在一个project的component中同时包含两个bsp，编译时有概率会导致函数重定义。

**Comment by TDA-2030** [comment]
box的bsp为了实现自适应两个硬件被重写了，而skainet的还是原来的。如果你使用的是box硬件，建议使用本仓库的bsp

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!
