### ISSUE TITLE
AFE_FETCH_CHANNEL_VERIFIED 的具体含义是什么？

### ISSUE THREAD

**Issue by bronya5th** [espressif/esp-box#26]
在[app_sr.c](https://github.com/espressif/esp-box/blob/efbfa327324a3a797cfff3be7eb6ff0fbf803f5f/examples/factory_demo/main/app/app_sr.c)中，
![Snipaste_2022-05-11_19-53-20](https://user-images.githubusercontent.com/44700918/167843567-d64956ae-7ffd-4dbe-a6f3-48d6dbd50b81.png)
AFE_FETCH_CHANNEL_VERIFIED感觉表示的是返回唤醒词识别成功，但在ESP-SR中显示的是返回音频通道确认，
![Snipaste_2022-05-11_19-52-05](https://user-images.githubusercontent.com/44700918/167843997-dd77e44c-503f-426c-ae53-a91f9bd9c307.png)
这个音频通道确认是指什么音频通道确认？

**Comment by WeldonWangwang** [comment]
Hi, @bronya5th 
此处的通道确认是因为在双麦算法中，2路麦克风数据经过前端信号处理后会分为 2 路处理后数据，其中一路是目标人声，一路是其他声音。当返回音频通道确认时，表明此时sr 算法已经找出 2 路中的目标人声所在通道，因此此时可以进行下一步语音识别，

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!
