### ISSUE TITLE
examples/facroty_demo build uses "cp" instead of "copy" on windows during "move model" task (AEGHB-272)

### ISSUE THREAD

**Issue by rysmith0315** [espressif/esp-box#3]
When building the "factory_demo", the build script is using "cp" on windows instead of "copy" during the "move model" task.

**Comment by ESP-Mars** [comment]
Kindly remind: we have updated the new application firmware, which updates the speech recognition model, add features of continuous identification, the GUI interface is compatible with current two box series development boards. You can download and experience it. https://github.com/espressif/esp-box

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!
