### ISSUE TITLE
factory_demo build fail

### ISSUE THREAD

**Issue by PaulskPt** [espressif/esp-box#35]
Hi, I tried to build the ```factory_demo``` however it failss with: 

/home/<user>/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/port_common.c:134: undefined reference to `app_main'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

In file: port_common.c, line 60 there is the definition: ```extern void app_main(void);```
and in line 135: ```app_main();```

I am using esp-idf version: ``` ESP-IDF v5.0-dev-3567-ge8d172eb87-dirty```.

I started the build process with: ```idf.py flash monitor```.

Can you please advice me how to get this build working?

**Comment by TDA-2030** [comment]
Have you changed the code? It looks like you might C file changed to cpp?

**Comment by PaulskPt** [comment]
Yes, I started to make preparations in file ap_sntp.c to try to add my Timezone to the present timezone options.
I did not create .cpp file(s). 

However, this morning I created a new clone of the esp-box repo. So I started with a 'clean' 1-to-1 copy. In esp-idf I first issued '. ./export.sh' to have the esp-idf environment OK. Then I went cd into the factory_demo folder. I put the esp32-s3-box into flash mode. Then I issued the command 'idf.py flash monitor'. This failed with some errors. 

Which version of esp-idf was Espressif using to build the factory_demo example for the ESP32-S3-BOX ?

**Comment by TDA-2030** [comment]
> Which version of esp-idf was Espressif using to build the factory_demo example for the ESP32-S3-BOX ?

https://github.com/espressif/esp-box#versions described the IDF requirement.

**Comment by PaulskPt** [comment]
Thank you. I deleted esp-idf and esp-box and re-installed both following the requirements and the 'getting started with esp-idf'. Now I was able to 'idf.py set-target esp32s3',  idf.py menuconfig and idf.py build without error (only one warning). Then I was able to monitor the factory_demo that was already running on the ESP32-S3-BOX.
For me, case, closed.
