### ISSUE TITLE
erase_flash 擦除设备之后，电脑无法正常识别此串口，断断续续不断重连电脑。

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-box#4]
问题描述：erase_flash 擦除设备之后，电脑无法正常识别此设备任意一串口，esp-box断断续续不断重连电脑。
操作系统：win10 专业版

**Comment by Real-YuZhe** [comment]
擦除 Flash 后，一级 Bootloader 会正常进入并初始化 USB Serial JTAG，但是二级 Bootloader 已经丢失，会导致启动失败而不断重启，从而不断链接 PC。
重新下载新固件即可解决该问题，如果想阻止重复连接的行为，可以尝试让设备进入下载模式，此时会一直等待烧录而不会重启
