### ISSUE TITLE
SD card with S3 Box

### ISSUE THREAD

**Issue by babadue** [espressif/esp-box#47]
Can one use SD card with the S3 Box?  Since the Box does not have a SD card slot, but it does have the USB-C.  Or any other way?

**Comment by ESP-Mars** [comment]
The device support Pmod™ compatible header, you can refer to the Pmod MicroSD module  https://digilent.com/reference/pmod/pmodmicrosd/start

**Comment by babadue** [comment]
> The device support Pmod™ compatible header, you can refer to the Pmod MicroSD module https://digilent.com/reference/pmod/pmodmicrosd/start

Indeed.  Thanks!
