### ISSUE TITLE
sd card and mp3_demo

### ISSUE THREAD

**Issue by babadue** [espressif/esp-box#50]
Trying to incorporate sd card with the mp3_demo for the S3 Box.   I could get the mp3_demo to play mp3 on the sd card with no problem.  Except the UI elements would not show up.  And vice versa if I got the UI working then the sd card will have issue.

The problem is down to these two initialization functions:
lv_port_init for LCD and spi_bus_initialize for the sd card.

Any hints what needed to be done?

Here are the errors. (Based on the sd card was initialized first)

E (880) spi_master: check_trans_valid(689): txdata transfer > host maximum
E (880) lcd_panel.io.spi: panel_io_spi_tx_color(358): spi transmit (queue) color failed
E (5890) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (5890) task_wdt:  - IDLE (CPU 0)
E (5890) task_wdt: Tasks currently running:
E (5890) task_wdt: CPU 0: lvgl_Task
E (5890) task_wdt: CPU 1: IDLE
E (5890) task_wdt: Print CPU 0 (current core) backtrace

**Comment by lijunru-hub** [comment]
You shouldn't let lvgl_task keep hogging system resources. You should add vTaskDelay

**Comment by babadue** [comment]
> You shouldn't let lvgl_task keep hogging system resources. You should add vTaskDelay

vTaskDelay was used.  The issue is that Box will not support SD card in SPI mode/protocol.  In MMC mode/protocol, it works fine in conjunction with active LCD.  Unless someone tells me I am wrong.
