### ISSUE TITLE
Running Detect and Feed Task on the same core

### ISSUE THREAD

**Issue by babadue** [espressif/esp-box#54]
Can you set these two tasks to run on the same core?    I have tried either both are on core 0 or core 1, but to no avail.

xTaskCreatePinnedToCore(&feed_Task, "feed", 8 * 1024, (void*)afe_data, 5, NULL, 0);
xTaskCreatePinnedToCore(&detect_Task, "detect", 8 * 1024, (void*)afe_data, 5, NULL, 1);

**Comment by espressif2022** [comment]
I've tried it, set them on the same core, it ok.

**Comment by babadue** [comment]
> 

You are right.  I got it to work!
