### ISSUE TITLE
A Talking Clock in Chinese (AEGHB-17)

### ISSUE THREAD

**Issue by babadue** [espressif/esp-box#56]
While going through those examples for the Box, I manage to copy and paste my way through a talking clock in Chinese.

[A Talking Clock in Chinese](https://github.com/babadue/talking_clock_chinese_esp32_s3_box)

Updated: 

01-22-2023 Ported over to IDF v5.0.
02-02-2023 Enable http server to upload mp3 files directly to the sd card.

**Comment by espressif2022** [comment]
> While going through those examples for the Box, I manage to copy and paste my way through a talking clock in Chinese.
> 
> [A Talking Clock in Chinese](https://github.com/babadue/talking_clock_chinese_esp32_s3_box)

I watched the demo video, it is a pretty good idea, do you have any plans for the follow-up?

**Comment by babadue** [comment]
> > While going through those examples for the Box, I manage to copy and paste my way through a talking clock in Chinese.
> > [A Talking Clock in Chinese](https://github.com/babadue/talking_clock_chinese_esp32_s3_box)
> 
> I watched the demo video, it is a pretty good idea, do you have any plans for the follow-up?

Probably add another feature using motion sensor and ESP32-CAM board.

**Comment by babadue** [comment]
Ported over to IDF v5.0

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!
