### ISSUE TITLE
[Schematic] Typo on the IMU MPN in the schematics

### ISSUE THREAD

**Issue by pedrominatel** [espressif/esp-box#6]
The part number in the schematics is wrong. The correct is ICM-42670-P and, not ICM-42607-P.

![Screenshot from 2021-12-06 13-05-42](https://user-images.githubusercontent.com/274658/144851276-cb4fe04b-b2f1-47ce-89bb-e8d525328fce.png)

**Comment by ESP-Mars** [comment]
Mass production used ICM-42607-P, ICM-42670-P and ICM-42607-P are pin to pin. The driver of it is developing now.

**Comment by pedrominatel** [comment]
Thank you @ESP-Mars!

**Comment by nishit-jain-esp** [comment]
If that is the case, then the name of the chip should be consistent on the first page of the [schematic](https://github.com/espressif/esp-box/blob/master/hardware/esp32_s3_box_v2.5/schematic/SCH_ESP32-S3-BOX_V2.5_20211011.pdf) and page 6. Also, the driver name in [code](https://github.com/espressif/esp-box/tree/master/components/i2c_devices/icm42670) should be the same as the actual chip being used.

**Comment by leeebo** [comment]
Fixed #6 in [b41dbb307](https://github.com/espressif/esp-box/tree/b41dbb307dfebc06879695b55d25352cedd5e095)
