### ISSUE TITLE
Build failure for factory_demo example (AEGHB-105)

### ISSUE THREAD

**Issue by Sundareswar23** [espressif/esp-box#60]
lcd_touch_tt21100/include -I/Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/managed_components/espressif__mdns/include -I/Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/managed_components/espressif__es7210/include -I/Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/managed_components/espressif__button/include -I/Users/sundareswarpalanichamy/projects/ESP/esp-box/components/bsp/src/boards -I/Users/sundareswarpalanichamy/projects/ESP/esp-box/components/bsp/include -I/Users/sundareswarpalanichamy/esp/old_esp/esp-idf/examples/common_components/iperf/include -I/Users/sundareswarpalanichamy/esp/old_esp/esp-idf/examples/common_components/protocol_examples_common/include -mlongcalls  -fdiagnostics-color=always -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo=. -fmacro-prefix-map=/Users/sundareswarpalanichamy/esp/old_esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0.1-3-g886e98a2c1\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -Wno-format -DBUTTON_VER_MAJOR=2 -DBUTTON_VER_MINOR=5 -DBUTTON_VER_PATCH=1 -DLV_LVGL_H_INCLUDE_SIMPLE -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/settings.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/settings.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/settings.c.obj -c /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/main/settings.c
In file included from /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/main/settings.h:9,
                 from /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/main/settings.c:15:
/Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/main/app/app_sr.h:14:10: fatal error: esp_afe_sr_models.h: No such file or directory
   14 | #include "esp_afe_sr_models.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[11/76] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/app/app_sntp.c.objninja: build stopped: subcommand failed.
HINT: Please make sure that the header name is correct. Also please check if you've specified all component dependencies with 'idf_component_register(REQUIRES ...)'. If the component is not present then it should be added by the IDF Component Manager. For more information run 'idf.py docs -sp api-guides/build-system.html'.
Also, please check if the header file has been removed, renamed or relocated - refer to the migration guide for more information.
ninja failed with exit code 1, output of the command is in the /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/build/log/idf_py_stderr_output_58118 and /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/build/log/idf_py_stdout_output_58118

**Comment by espressif2022** [comment]
we are updating SR component now, this will be fixed as soon as possilbe.

**Comment by Sundareswar23** [comment]
@espressif2022  can you please update rainmaker component also, below error occurs

`r/src/console/esp_rmaker_console.c
/Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/managed_components/espressif__esp_rainmaker/src/console/esp_rmaker_console.c:16:10: fatal error: esp_rmaker_common_console.h: No such file or directory
   16 | #include <esp_rmaker_common_console.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[1/1] cd /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/build/bootloader/esp-id... /Users/sundareswarpalanichamy/projects/ESP/esp-box/examples/factory_demo/build/bootloader/bootloader.binBootloader binary size 0x5600 bytes. 0x2a00 bytes (33%) free.`

**Comment by espressif2022** [comment]
espressif/esp_rainmaker:
    path: components/esp_rainmaker
    git: https://github.com/espressif/esp-rainmaker.git
    version: "b863717a86e8a3bd987aac95670c0817233f2a6a"
  espressif/esp_schedule:
    path: components/esp_schedule
    git: https://github.com/espressif/esp-rainmaker.git
    version: "b863717a86e8a3bd987aac95670c0817233f2a6a"

**Comment by Sundareswar23** [comment]
can we have latest rainmaker version ?

**Comment by espressif2022** [comment]
> 

we'll fixed this, you can try this version current now.
