### ISSUE TITLE
watering_demo中存在idf版本冲突问题。 (AEGHB-129)

### ISSUE THREAD

**Issue by MeowStatus** [espressif/esp-box#64]
如题。
idf_component.yml中要求idf≥5.0，然而该demo的readme中要求idf版本为v4.4。
结果无论用5.0还是4.4都不能成功编译该例程。
其他例程中也有类似的问题，望尽快修复。

**Comment by espressif2022** [comment]
在 ESP-IDF 5.0 上，是 esp-rainmaker 编译失败吗？

**Comment by MeowStatus** [comment]
> 在 ESP-IDF 5.0 上，是 esp-rainmaker 编译失败吗？
是。
factory_demo中也是同样的问题。
相关log如下：
![image](https://user-images.githubusercontent.com/79510201/230317679-e6d7216c-a580-4272-a93a-fddc955fe5f2.png)

**Comment by espressif2022** [comment]
稍等，验证有问题。我换个 version， 验证一下，一会回复

**Comment by espressif2022** [comment]
> > 在 ESP-IDF 5.0 上，是 esp-rainmaker 编译失败吗？
> 
> 是。 factory_demo中也是同样的问题。 相关log如下： ![image](https://user-images.githubusercontent.com/79510201/230317679-e6d7216c-a580-4272-a93a-fddc955fe5f2.png)

https://github.com/espressif/esp-box/issues/60 麻烦先参考这个 issue，验证 ok，谢谢。

**Comment by MeowStatus** [comment]
> #60 麻烦先参考这个 issue，验证 ok，谢谢。

验证可行，感谢！
此issue您可关闭。

**Comment by espressif2022** [comment]
> > #60 麻烦先参考这个 issue，验证 ok，谢谢。
> 
> 验证可行，感谢！ 此issue您可关闭。

请帮忙 close 下，我这好像没权限
