### ISSUE TITLE
我想把uac，hid的代码移植到我其他的项目上，需要把哪些部分移植过去呢？ (AEGHB-137)

### ISSUE THREAD

**Issue by weiqifa0** [espressif/esp-box#66]
我尝试直接拷贝headset下面的核心代码过去，发现有非常多的错误。

**Comment by weiqifa0** [comment]
https://github.com/weiqifa0/esp-box

我把代码放到了这个位置

**Comment by weiqifa0** [comment]
在headset例子程序里面

**Comment by weiqifa0** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/11375905/230735110-0b769ec9-f3ae-4d14-ab1a-4bfa6d9969c4.png">
我已经把需要的放到这个位置了，但是编译的时候还是提示找不到文件。

[8/19] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/src/page_fft.c.objFAILED: esp-idf/main/CMakeFiles/__idf_main.dir/src/page_fft.c.obj
/Users/crisqifawei/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc -DLV_CONF_INCLUDE_SIMPLE -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/build/config -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/main/include -I/Users/crisqifawei/esp/esp-idf/components/newlib/platform_include -I/Users/crisqifawei/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/Users/crisqifawei/esp/esp-idf/components/freertos/esp_additions/include/freertos -I/Users/crisqifawei/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/Users/crisqifawei/esp/esp-idf/components/freertos/esp_additions/include -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/include -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/include/soc -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/include/soc/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/port/esp32s3/. -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/port/esp32s3/private_include -I/Users/crisqifawei/esp/esp-idf/components/heap/include -I/Users/crisqifawei/esp/esp-idf/components/log/include -I/Users/crisqifawei/esp/esp-idf/components/soc/include -I/Users/crisqifawei/esp/esp-idf/components/soc/esp32s3/. -I/Users/crisqifawei/esp/esp-idf/components/soc/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/hal/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/hal/include -I/Users/crisqifawei/esp/esp-idf/components/hal/platform_port/include -I/Users/crisqifawei/esp/esp-idf/components/esp_rom/include -I/Users/crisqifawei/esp/esp-idf/components/esp_rom/include/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_rom/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_common/include -I/Users/crisqifawei/esp/esp-idf/components/esp_system/include -I/Users/crisqifawei/esp/esp-idf/components/esp_system/port/soc -I/Users/crisqifawei/esp/esp-idf/components/esp_system/port/include/private -I/Users/crisqifawei/esp/esp-idf/components/xtensa/include -I/Users/crisqifawei/esp/esp-idf/components/xtensa/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/include/apps -I/Users/crisqifawei/esp/esp-idf/components/lwip/include/apps/sntp -I/Users/crisqifawei/esp/esp-idf/components/lwip/lwip/src/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/port/esp32/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/port/esp32/include/arch -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__es7210/include -I/Users/crisqifawei/esp/esp-idf/components/driver/include -I/Users/crisqifawei/esp/esp-idf/components/driver/deprecated -I/Users/crisqifawei/esp/esp-idf/components/driver/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/esp_pm/include -I/Users/crisqifawei/esp/esp-idf/components/esp_ringbuf/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-box/include -I/Users/crisqifawei/esp/esp-idf/components/spiffs/include -I/Users/crisqifawei/esp/esp-idf/components/esp_partition/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_codec_dev/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_codec_dev/interface -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_codec_dev/device/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_lvgl_port/include -I/Users/crisqifawei/esp/esp-idf/components/esp_lcd/include -I/Users/crisqifawei/esp/esp-idf/components/esp_lcd/interface -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/lvgl__lvgl -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/lvgl__lvgl/src -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/dotprod/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/support/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/hann/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/blackman/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/blackman_harris/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/blackman_nuttall/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/nuttall/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/flat_top/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/iir/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/fir/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/add/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/sub/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/mul/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/addc/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/mulc/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/sqrt/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/matrix/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/fft/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/dct/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/conv/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/common/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/kalman/ekf/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src -I/Users/crisqifawei/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos -I/Users/crisqifawei/esp/esp-idf/components/efuse/include -I/Users/crisqifawei/esp/esp-idf/components/efuse/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/port/include -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/mbedtls/include -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/mbedtls/library -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I/Users/crisqifawei/esp/esp-idf/components/esp_app_format/include -I/Users/crisqifawei/esp/esp-idf/components/bootloader_support/include -I/Users/crisqifawei/esp/esp-idf/components/bootloader_support/bootloader_flash/include -I/Users/crisqifawei/esp/esp-idf/components/app_update/include -I/Users/crisqifawei/esp/esp-idf/components/spi_flash/include -I/Users/crisqifawei/esp/esp-idf/components/pthread/include -I/Users/crisqifawei/esp/esp-idf/components/esp_timer/include -I/Users/crisqifawei/esp/esp-idf/components/app_trace/include -I/Users/crisqifawei/esp/esp-idf/components/esp_event/include -I/Users/crisqifawei/esp/esp-idf/components/nvs_flash/include -I/Users/crisqifawei/esp/esp-idf/components/esp_phy/include -I/Users/crisqifawei/esp/esp-idf/components/esp_phy/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/vfs/include -I/Users/crisqifawei/esp/esp-idf/components/esp_netif/include -I/Users/crisqifawei/esp/esp-idf/components/wpa_supplicant/include -I/Users/crisqifawei/esp/esp-idf/components/wpa_supplicant/port/include -I/Users/crisqifawei/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include -I/Users/crisqifawei/esp/esp-idf/components/esp_wifi/include -I/Users/crisqifawei/esp/esp-idf/components/unity/include -I/Users/crisqifawei/esp/esp-idf/components/unity/unity/src -I/Users/crisqifawei/esp/esp-idf/components/cmock/CMock/src -I/Users/crisqifawei/esp/esp-idf/components/console -I/Users/crisqifawei/esp/esp-idf/components/http_parser -I/Users/crisqifawei/esp/esp-idf/components/esp-tls -I/Users/crisqifawei/esp/esp-idf/components/esp-tls/esp-tls-crypto -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/include -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/interface -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/deprecated/include -I/Users/crisqifawei/esp/esp-idf/components/esp_eth/include -I/Users/crisqifawei/esp/esp-idf/components/esp_gdbstub/include -I/Users/crisqifawei/esp/esp-idf/components/esp_gdbstub/xtensa -I/Users/crisqifawei/esp/esp-idf/components/esp_gdbstub/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_hid/include -I/Users/crisqifawei/esp/esp-idf/components/tcp_transport/include -I/Users/crisqifawei/esp/esp-idf/components/esp_http_client/include -I/Users/crisqifawei/esp/esp-idf/components/esp_http_server/include -I/Users/crisqifawei/esp/esp-idf/components/esp_https_ota/include -I/Users/crisqifawei/esp/esp-idf/components/protobuf-c/protobuf-c -I/Users/crisqifawei/esp/esp-idf/components/protocomm/include/common -I/Users/crisqifawei/esp/esp-idf/components/protocomm/include/security -I/Users/crisqifawei/esp/esp-idf/components/protocomm/include/transports -I/Users/crisqifawei/esp/esp-idf/components/esp_local_ctrl/include -I/Users/crisqifawei/esp/esp-idf/components/esp_psram/include -I/Users/crisqifawei/esp/esp-idf/components/espcoredump/include -I/Users/crisqifawei/esp/esp-idf/components/espcoredump/include/port/xtensa -I/Users/crisqifawei/esp/esp-idf/components/wear_levelling/include -I/Users/crisqifawei/esp/esp-idf/components/sdmmc/include -I/Users/crisqifawei/esp/esp-idf/components/fatfs/diskio -I/Users/crisqifawei/esp/esp-idf/components/fatfs/vfs -I/Users/crisqifawei/esp/esp-idf/components/fatfs/src -I/Users/crisqifawei/esp/esp-idf/components/idf_test/include -I/Users/crisqifawei/esp/esp-idf/components/idf_test/include/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/ieee802154/include -I/Users/crisqifawei/esp/esp-idf/components/json/cJSON -I/Users/crisqifawei/esp/esp-idf/components/mqtt/esp-mqtt/include -I/Users/crisqifawei/esp/esp-idf/components/perfmon/include -I/Users/crisqifawei/esp/esp-idf/components/touch_element/include -I/Users/crisqifawei/esp/esp-idf/components/ulp/ulp_common/include -I/Users/crisqifawei/esp/esp-idf/components/ulp/ulp_common/include/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/usb/include -I/Users/crisqifawei/esp/esp-idf/components/wifi_provisioning/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_lcd_touch/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_lcd_touch_tt21100/include -mlongcalls  -fdiagnostics-color=always -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/Users/crisqifawei/esp/esp-box/examples/usb_headset=. -fmacro-prefix-map=/Users/crisqifawei/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0.1\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -DCFG_TUSB_MCU=OPT_MCU_ESP32S3 -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/src/page_fft.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/src/page_fft.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/src/page_fft.c.obj -c /Users/crisqifawei/esp/esp-box/examples/usb_headset/main/src/page_fft.c
In file included from /Users/crisqifawei/esp/esp-box/examples/usb_headset/main/src/page_fft.c:10:
/Users/crisqifawei/esp/esp-box/examples/usb_headset/main/include/page_fft.h:32:10: fatal error: lv_ex_conf.h: No such file or directory
   32 | #include "lv_ex_conf.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
[9/19] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/src/usb_descriptors.c.objIn file included from /Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src/tusb_option.h:184,
                 from /Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src/common/tusb_common.h:70,
                 from /Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src/tusb.h:37,
                 from /Users/crisqifawei/esp/esp-box/examples/usb_headset/main/src/usb_descriptors.c:6:
/Users/crisqifawei/esp/esp-box/examples/usb_headset/main/include/tusb_config.h:36:22: warning: extra tokens at end of #ifndef directive
   36 | #ifndef CFG_TUSB_MCU OPT_MCU_LPC175X_6X
      |                      ^~~~~~~~~~~~~~~~~~
[10/19] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/main.c.objFAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj
/Users/crisqifawei/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc -DLV_CONF_INCLUDE_SIMPLE -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/build/config -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/main/include -I/Users/crisqifawei/esp/esp-idf/components/newlib/platform_include -I/Users/crisqifawei/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/Users/crisqifawei/esp/esp-idf/components/freertos/esp_additions/include/freertos -I/Users/crisqifawei/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/Users/crisqifawei/esp/esp-idf/components/freertos/esp_additions/include -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/include -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/include/soc -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/include/soc/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/port/esp32s3/. -I/Users/crisqifawei/esp/esp-idf/components/esp_hw_support/port/esp32s3/private_include -I/Users/crisqifawei/esp/esp-idf/components/heap/include -I/Users/crisqifawei/esp/esp-idf/components/log/include -I/Users/crisqifawei/esp/esp-idf/components/soc/include -I/Users/crisqifawei/esp/esp-idf/components/soc/esp32s3/. -I/Users/crisqifawei/esp/esp-idf/components/soc/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/hal/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/hal/include -I/Users/crisqifawei/esp/esp-idf/components/hal/platform_port/include -I/Users/crisqifawei/esp/esp-idf/components/esp_rom/include -I/Users/crisqifawei/esp/esp-idf/components/esp_rom/include/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_rom/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_common/include -I/Users/crisqifawei/esp/esp-idf/components/esp_system/include -I/Users/crisqifawei/esp/esp-idf/components/esp_system/port/soc -I/Users/crisqifawei/esp/esp-idf/components/esp_system/port/include/private -I/Users/crisqifawei/esp/esp-idf/components/xtensa/include -I/Users/crisqifawei/esp/esp-idf/components/xtensa/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/include/apps -I/Users/crisqifawei/esp/esp-idf/components/lwip/include/apps/sntp -I/Users/crisqifawei/esp/esp-idf/components/lwip/lwip/src/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/port/esp32/include -I/Users/crisqifawei/esp/esp-idf/components/lwip/port/esp32/include/arch -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__es7210/include -I/Users/crisqifawei/esp/esp-idf/components/driver/include -I/Users/crisqifawei/esp/esp-idf/components/driver/deprecated -I/Users/crisqifawei/esp/esp-idf/components/driver/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/esp_pm/include -I/Users/crisqifawei/esp/esp-idf/components/esp_ringbuf/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-box/include -I/Users/crisqifawei/esp/esp-idf/components/spiffs/include -I/Users/crisqifawei/esp/esp-idf/components/esp_partition/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_codec_dev/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_codec_dev/interface -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_codec_dev/device/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_lvgl_port/include -I/Users/crisqifawei/esp/esp-idf/components/esp_lcd/include -I/Users/crisqifawei/esp/esp-idf/components/esp_lcd/interface -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/lvgl__lvgl -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/lvgl__lvgl/src -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/dotprod/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/support/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/hann/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/blackman/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/blackman_harris/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/blackman_nuttall/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/nuttall/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/windows/flat_top/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/iir/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/fir/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/add/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/sub/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/mul/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/addc/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/mulc/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/math/sqrt/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/matrix/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/fft/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/dct/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/conv/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/common/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/kalman/ekf/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src -I/Users/crisqifawei/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos -I/Users/crisqifawei/esp/esp-idf/components/efuse/include -I/Users/crisqifawei/esp/esp-idf/components/efuse/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/port/include -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/mbedtls/include -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/mbedtls/library -I/Users/crisqifawei/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I/Users/crisqifawei/esp/esp-idf/components/esp_app_format/include -I/Users/crisqifawei/esp/esp-idf/components/bootloader_support/include -I/Users/crisqifawei/esp/esp-idf/components/bootloader_support/bootloader_flash/include -I/Users/crisqifawei/esp/esp-idf/components/app_update/include -I/Users/crisqifawei/esp/esp-idf/components/spi_flash/include -I/Users/crisqifawei/esp/esp-idf/components/pthread/include -I/Users/crisqifawei/esp/esp-idf/components/esp_timer/include -I/Users/crisqifawei/esp/esp-idf/components/app_trace/include -I/Users/crisqifawei/esp/esp-idf/components/esp_event/include -I/Users/crisqifawei/esp/esp-idf/components/nvs_flash/include -I/Users/crisqifawei/esp/esp-idf/components/esp_phy/include -I/Users/crisqifawei/esp/esp-idf/components/esp_phy/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/vfs/include -I/Users/crisqifawei/esp/esp-idf/components/esp_netif/include -I/Users/crisqifawei/esp/esp-idf/components/wpa_supplicant/include -I/Users/crisqifawei/esp/esp-idf/components/wpa_supplicant/port/include -I/Users/crisqifawei/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include -I/Users/crisqifawei/esp/esp-idf/components/esp_wifi/include -I/Users/crisqifawei/esp/esp-idf/components/unity/include -I/Users/crisqifawei/esp/esp-idf/components/unity/unity/src -I/Users/crisqifawei/esp/esp-idf/components/cmock/CMock/src -I/Users/crisqifawei/esp/esp-idf/components/console -I/Users/crisqifawei/esp/esp-idf/components/http_parser -I/Users/crisqifawei/esp/esp-idf/components/esp-tls -I/Users/crisqifawei/esp/esp-idf/components/esp-tls/esp-tls-crypto -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/include -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/interface -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/esp32s3/include -I/Users/crisqifawei/esp/esp-idf/components/esp_adc/deprecated/include -I/Users/crisqifawei/esp/esp-idf/components/esp_eth/include -I/Users/crisqifawei/esp/esp-idf/components/esp_gdbstub/include -I/Users/crisqifawei/esp/esp-idf/components/esp_gdbstub/xtensa -I/Users/crisqifawei/esp/esp-idf/components/esp_gdbstub/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/esp_hid/include -I/Users/crisqifawei/esp/esp-idf/components/tcp_transport/include -I/Users/crisqifawei/esp/esp-idf/components/esp_http_client/include -I/Users/crisqifawei/esp/esp-idf/components/esp_http_server/include -I/Users/crisqifawei/esp/esp-idf/components/esp_https_ota/include -I/Users/crisqifawei/esp/esp-idf/components/protobuf-c/protobuf-c -I/Users/crisqifawei/esp/esp-idf/components/protocomm/include/common -I/Users/crisqifawei/esp/esp-idf/components/protocomm/include/security -I/Users/crisqifawei/esp/esp-idf/components/protocomm/include/transports -I/Users/crisqifawei/esp/esp-idf/components/esp_local_ctrl/include -I/Users/crisqifawei/esp/esp-idf/components/esp_psram/include -I/Users/crisqifawei/esp/esp-idf/components/espcoredump/include -I/Users/crisqifawei/esp/esp-idf/components/espcoredump/include/port/xtensa -I/Users/crisqifawei/esp/esp-idf/components/wear_levelling/include -I/Users/crisqifawei/esp/esp-idf/components/sdmmc/include -I/Users/crisqifawei/esp/esp-idf/components/fatfs/diskio -I/Users/crisqifawei/esp/esp-idf/components/fatfs/vfs -I/Users/crisqifawei/esp/esp-idf/components/fatfs/src -I/Users/crisqifawei/esp/esp-idf/components/idf_test/include -I/Users/crisqifawei/esp/esp-idf/components/idf_test/include/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/ieee802154/include -I/Users/crisqifawei/esp/esp-idf/components/json/cJSON -I/Users/crisqifawei/esp/esp-idf/components/mqtt/esp-mqtt/include -I/Users/crisqifawei/esp/esp-idf/components/perfmon/include -I/Users/crisqifawei/esp/esp-idf/components/touch_element/include -I/Users/crisqifawei/esp/esp-idf/components/ulp/ulp_common/include -I/Users/crisqifawei/esp/esp-idf/components/ulp/ulp_common/include/esp32s3 -I/Users/crisqifawei/esp/esp-idf/components/usb/include -I/Users/crisqifawei/esp/esp-idf/components/wifi_provisioning/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_lcd_touch/include -I/Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__esp_lcd_touch_tt21100/include -mlongcalls  -fdiagnostics-color=always -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/Users/crisqifawei/esp/esp-box/examples/usb_headset=. -fmacro-prefix-map=/Users/crisqifawei/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0.1\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -DCFG_TUSB_MCU=OPT_MCU_ESP32S3 -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c /Users/crisqifawei/esp/esp-box/examples/usb_headset/main/main.c
In file included from /Users/crisqifawei/esp/esp-box/examples/usb_headset/main/main.c:12:
/Users/crisqifawei/esp/esp-box/examples/usb_headset/main/include/page_fft.h:32:10: fatal error: lv_ex_conf.h: No such file or directory
   32 | #include "lv_ex_conf.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
[11/19] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/__/managed_components/espressif__tinyusb/src/portable/synopsys/dwc2/dcd_dwc2.c.objIn file included from /Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src/tusb_option.h:184,
                 from /Users/crisqifawei/esp/esp-box/examples/usb_headset/managed_components/espressif__tinyusb/src/portable/synopsys/dwc2/dcd_dwc2.c:30:
/Users/crisqifawei/esp/esp-box/examples/usb_headset/main/include/tusb_config.h:36:22: warning: extra tokens at end of #ifndef directive
   36 | #ifndef CFG_TUSB_MCU OPT_MCU_LPC175X_6X
      |                      ^~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
HINT: Please make sure that the header name is correct. Also please check if you've specified all component dependencies with 'idf_component_register(REQUIRES ...)'. If the component is not present then it should be added by the IDF Component Manager. For more information run 'idf.py docs -sp api-guides/build-system.html'.
Also, please check if the header file has been removed, renamed or relocated - refer to the migration guide for more information.
ninja failed with exit code 1, output of the command is in the /Users/crisqifawei/esp/esp-box/examples/usb_headset/build/log/idf_py_stderr_output_35331 and /Users/crisqifawei/esp/esp-box/examples/usb_headset/build/log/idf_py_stdout_output_35331
(base) crisqifawei@CRISQIFAWEI-MC0 usb_headset %

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!

**Comment by lijunru-hub** [comment]
你的 lvgl 目录下面有文件吗？大概率是没有拉取子模块。
使用 git submodule update --init --recursive 拉取子模块
