### ISSUE TITLE
Feature request - Matter (AEGHB-150)

### ISSUE THREAD

**Issue by a-d-r-i-a-n-d** [espressif/esp-box#68]
Hi there,

I think the ESP32-S3-BOX could be an excellent device if it supported Matter. Imagine being able to commission and control all your Matter-compatible devices from one centralized hub - that would be fantastic! I realize this could be a significant change in terms of demand and the types of buyers, as it would appeal not only to developers and enthusiasts, but also to regular consumers.

My question is: does the ESP32-S3-BOX have enough resources to function as a Matter server, controller, and commissioner?

Thank you for your consideration!

**Comment by espressif2022** [comment]
> Hi there,
> 
> I think the ESP32-S3-BOX could be an excellent device if it supported Matter. Imagine being able to commission and control all your Matter-compatible devices from one centralized hub - that would be fantastic! I realize this could be a significant change in terms of demand and the types of buyers, as it would appeal not only to developers and enthusiasts, but also to regular consumers.
> 
> My question is: does the ESP32-S3-BOX have enough resources to function as a Matter server, controller, and commissioner?
> 
> Thank you for your consideration!

Thanks for your suggestion.
 We have a Matter project internally, and it will be released in the near future.

**Comment by a-d-r-i-a-n-d** [comment]
Great news, looking forward to it.

**Comment by ESP-Mars** [comment]
@a-d-r-i-a-n-d Hi we have release a matter switch demo for user to enjoy! https://github.com/espressif/esp-box/tree/master/examples/matter_switch
