### ISSUE TITLE
what is the different between ESP32-S3-BOX and ESP32-S3-Korvo-1 board? (AEGHB-170)

### ISSUE THREAD

**Issue by IamFive** [espressif/esp-box#70]
it seems `esp32-s3-box` have all features that `ESP32-S3-Korvo-1` have, am I right?
For examples which need `ESP32-S3-Korvo-1`, can we use `ESP32-S3-BOX` instead?

**Comment by espressif2022** [comment]
> ESP32-S3-Korvo-1

yeah， esp32-s3-box have all features of ESP32-S3-Korvo-1.
