### ISSUE TITLE
刷入example中的usb_headset后，串口无法识别，无法刷入其他任何程序 (AEGHB-171)

### ISSUE THREAD

**Issue by Mr-KID-github** [espressif/esp-box#71]
![image](https://user-images.githubusercontent.com/80014289/236634174-208e6362-caa5-4d65-9590-01f19fd4f308.png)

**Comment by espressif2022** [comment]
com7 是否存在，window 的 flash_download_tool 是否可以烧写 ？

**Comment by suyulin** [comment]
同时 按住 boot 和 reset ,即可恢复。

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!

**Comment by kingaza** [comment]
我也遇到同样的问题，似乎也只有这个example才会这样子。
为啥呢？

**Comment by ESP-Mars** [comment]
> 我也遇到同样的问题，似乎也只有这个example才会这样子。 为啥呢？

原因就是 USB 被应用程序占用了，所以无法自动进入下载模式，需要手动进入。
