### ISSUE TITLE
[问题] 有关于S3上搭建神经网络模型的demo吗？  (AEGHB-189)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-box#74]
如题， 因为S3支持AI加速，但是没有找到相关的例子

**Comment by ESP-Mars** [comment]
Here is a tutorial to guide users in deploying a classification model on the ESP32-S3. We hope this guide proves helpful to you.
https://blog.espressif.com/hand-gesture-recognition-on-esp32-s3-with-esp-deep-learning-176d7e13fd37

**Comment by fatsheep2020** [comment]
ok, good example, thanks!
