### ISSUE TITLE
[求助]ESP32-S3-Box 无法更新固件 (AEGHB-191)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-box#75]
使用windows下的"flash_download_tool" 更新BOX的固件，参考这里的：
https://github.com/espressif/esp-box/blob/master/docs/firmware_update_cn.md
[但是更新完以后，box不停的重启，现象是电脑的USB串口不停的连接断开。
感谢~
![issue1](https://github.com/espressif/esp-box/assets/60244699/aa3f0486-af01-447a-ac3e-c1ea388f98dd)
先擦除，显示成功
![issue2](https://github.com/espressif/esp-box/assets/60244699/80f4b1b5-4e75-4650-a703-a908cbb443e4)
刷写固件，显示成功

**Comment by ESP-Mars** [comment]
你同时按住 boot 和 reset，手动进入下载模式试一试。

**Comment by fatsheep2020** [comment]
现在可以了！
