### ISSUE TITLE
【求助】关于ESP-DL (AEGHB-197)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-box#76]
DL的官方安装和使用例子是基于linux的：https://github.com/espressif/esp-dl/tree/master/examples/human_face_detect
有没有基于windows的，还是只能在linux下使用？
谢谢！

**Comment by alibukharai** [comment]
> DL的官方安装和使用例子是基于linux的：https://github.com/espressif/esp-dl/tree/master/examples/human_face_detect 有没有基于windows的，还是只能在linux下使用？ 谢谢！
The provided example should be compatible with both Linux and Windows operating systems, However If you could specify the required commands, I would be able to provide you with more details.

**Comment by fatsheep2020** [comment]
hi, Ali:
Thanks for your answer!  i prefer to use it in windows, since my IDF was run in windows. could you give some guide?

**Comment by fatsheep2020** [comment]
it can works in my windows VSCode! thanks for your reminder!
