### ISSUE TITLE
[help] how to add a component in the current project (AEGHB-236)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-box#79]
Environment: VSCode+IDF plugin, windows
i don't know how to add a component into an existing project, for example add an wi-fi component into helloworld project.
(怎样给一个已有的项目添加组件，具体是怎样的流程，是通过手写还是配置来实现的？）
Thanks!

**Comment by espressif2022** [comment]
例如 wifi 的话，你可以参考 ESP-IDF下的 example/WiFi/getting_started 例程.

**Comment by fatsheep2020** [comment]
ok, thanks!
