### ISSUE TITLE
iPhone app crashes when registering ESP-Box (AEGHB-245)

### ISSUE THREAD

**Issue by bluepuma77** [espressif/esp-box#80]
When trying to register the ESP-Box with the iPhone app, the app scans the code, says "connecting" and then just crashes. When I open the app again, the device is not registered. Trying to register again crashes the app.

The iPhone app itself has a [link for support](https://www.espressif.com/en/contact-us/technical-inquiries), but the website crashes, too:

> Error message
PDOException: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111) in lock_may_be_available() (line 167 of /var/www/html/includes/lock.inc).

**Comment by ESP-Mars** [comment]
Thanks for your feedback. What's your iPhone model and iOS version?

**Comment by bluepuma77** [comment]
iPhone SE3, it was the latest version before 16.5.

Over night the iPhone was updated to 16.5 and I now have CircuitPython installed on the ESP32-Box.

**Comment by ESP-Mars** [comment]
We will debug and solve this issue.

**Comment by ESP-Mars** [comment]
We solved and will update the APP, but now is blocked by an issue of Apple Developer, please track the progress through this issue https://github.com/espressif/esp-box/issues/80

**Comment by ESP-Mars** [comment]
The bug has been fixed, please update your ESP-BOX from App Store.

**Comment by ESP-Mars** [comment]
Resolved by https://github.com/espressif/esp-box/issues/72. I will now close this issue. If you have any further questions or concerns, feel free to reopen it.
