### ISSUE TITLE
box changed color in sunlight (AEGHB-246)

### ISSUE THREAD

**Issue by mars3142** [espressif/esp-box#81]
The ESP-Box is on my desk and the sun is shining into my room directly. Now after some time, the box changed color. This isn't good. What's the material? It should get a revision ;)

![IMG_1868](https://github.com/espressif/esp-box/assets/220423/4142468b-ea08-49c8-92d9-68efa62fff07)
![IMG_1867](https://github.com/espressif/esp-box/assets/220423/a1cd0db4-6a44-459e-bc25-06c1495b32c0)

**Comment by ESP-Mars** [comment]
Thanks for your feedback, the observed discoloration issue with this material we will consider making improvements in the future. This material is photosensitive resin, suitable for general product casing verification and common assembly parts, offering a high cost-performance ratio.

**Comment by ESP-Mars** [comment]
Hi, if you don't have any questions, please close this issue. Thank you!
