### ISSUE TITLE
First page is empty at startup for M5Stack CoreS3 ESP32S3  (AEGHB-248)

### ISSUE THREAD

**Issue by lboue** [espressif/esp-box#82]
Hello,

I flashed CoreS3-Box demo for M5 Burner:  
![image](https://github.com/espressif/esp-box/assets/938089/2cca6028-2051-4107-9ca3-48d832b47e53)

It noticed first page is empty for M5Stack CoreS3 ESP32S3. What is the purpose of having an empty page?

![IMG-3150](https://github.com/espressif/esp-box/assets/938089/7ed5bc6b-3b4f-4aea-a61f-49b0b96bcd51)

Related to: https://github.com/m5stack/CoreS3-Box/tree/dev-cores3

**Comment by imliubo** [comment]
Hi @lboue , I open the issue on CoreS3 repo, so you can ask there. And the hardware is a little different, so we stiil need do  some work on this. I will check this. Thanks for report. :)

**Comment by lboue** [comment]
> Hi @lboue , I open the issue on CoreS3 repo, so you can ask there. And the hardware is a little different, so we stiil need do some work on this. I will check this. Thanks for report. :)

Thanks

**Comment by lboue** [comment]
@imliubo I am sorry but I can't find your issue here:
1. https://github.com/m5stack/CoreS3-Box/issues
2. https://github.com/m5stack/M5CoreS3/issues

**Comment by imliubo** [comment]
Related discussion moved to [here](https://github.com/m5stack/CoreS3-Box/issues/1).

**Comment by ESP-Mars** [comment]
Close the issue since it moved to another external project.
