### ISSUE TITLE
audio output distorted in usb_headset example (AEGHB-258)

### ISSUE THREAD

**Issue by mjhewitt1** [espressif/esp-box#84]
When using the example 'usb_headset' (unchanged) the audio output is distorted (sounds like it is skipping/cutting out). Any similar issues/ideas how to fix this? 
Many thanks

**Comment by leeebo** [comment]
Hi @mjhewitt1 Would you please try with the prebuilt binary from [esp-box launchpad](https://espressif.github.io/esp-launchpad/?flashConfigURL=https://raw.githubusercontent.com/espressif/esp-box/master/launch.toml), choose usb_headset then flash to give it a try

**Comment by mjhewitt1** [comment]
Hi, thanks for your response. I have given it a go and still sounds the same unfortunately

**Comment by lijunru-hub** [comment]
Are you using a windows computer? What is the version of windwos

**Comment by mjhewitt1** [comment]
Ah so, I have tried on a Windows 10 computer and it works! But no luck on Ubuntu 20.04

**Comment by mjhewitt1** [comment]
Hi there, I have fixed the issue :) 

I used the esp-box launchpad site to connect and flash the USB headset example to the ESP-BOX. The audio output was fine when I did this on a Windows PC, but not on Ubuntu. 

I fixed the issue with the audio output on Ubuntu by adding the following lines to /etc/pulse/daemon.conf : 
default-sample-rate = 48000
alternate-sample-rate = 48000

Which was suggested here -- https://askubuntu.com/questions/1399384/ubuntu-audio-crackling-using-logitech-usb-audio-even-after-formatting 

Thanks a lot for your responses
