### ISSUE TITLE
chatgptdemo能否支持box-lite (AEGHB-325)

### ISSUE THREAD

**Issue by wangbaojunbuaa** [espressif/esp-box#88]
小白一枚，实在买不到esp32s3-box，就买了box-lie。拿到手以后发现官方的demo不支持lite，哪位大神有解决办法，谢谢！

**Comment by espressif2022** [comment]
仓库示例是可以支持，具体是运行哪个 demo 出现问题？

**Comment by wangbaojunbuaa** [comment]
> 稍等下，我们的 MR 在推进中，最近几天就 OK. 如果想先尝试，可以试下该 commit：2bce6c5281940722877f1b1643dc0506c7cf7fbd 这分 commit 不支持电脑导入配置，需要在 menuconfig 配置

谢谢！！！

**Comment by espressif2022** [comment]
已 release，麻烦确认下。

**Comment by wangbaojunbuaa** [comment]
> 已 release，麻烦确认下。

ok 感谢感谢，速度真快
