### ISSUE TITLE
USB连接问题 (AEGHB-356)

### ISSUE THREAD

**Issue by undefinedcodezhong** [espressif/esp-box#89]
Windows10系统，esp32s3box-lite 使用USB连接后显示未识别设备，设备管理器的端口哪里也没有显示COM端口，应该怎么处理？

**Comment by espressif2022** [comment]
> Windows10系统，esp32s3box-lite 使用USB连接后显示未识别设备，设备管理器的端口哪里也没有显示COM端口，应该怎么处理？

烧录的哪个 demo ？

**Comment by undefinedcodezhong** [comment]
ESP-BOX-Lite_Demo_CN_VO_5_0这个demo
在线固件烧录工具 ESP Launchpad的显示情况
![d14e82ce78a63325f0a060726754f92](https://github.com/espressif/esp-box/assets/40236765/41c08184-29b9-477f-8c86-e655122ee758)
设备管理器界面：
![image](https://github.com/espressif/esp-box/assets/40236765/d3a6b804-63da-470a-a1d3-4b9e077a7dcd)
linux系统也找不到串口设备
![4833d719c28368c5b01c81f8e27e76a](https://github.com/espressif/esp-box/assets/40236765/97d0aadd-61d2-4805-873e-66e16fd96255)

**Comment by alibukharai** [comment]
@undefinedcodezhong I recommend attempting to enter download mode manually by holding down the Boot button and simultaneously pressing the EN button.

**Comment by espressif2022** [comment]
前面有烧写 usbheadset 之类占用 USB 的固件？

**Comment by undefinedcodezhong** [comment]
> @undefinedcodezhong I recommend attempting to enter download mode manually by holding down the Boot button and simultaneously pressing the EN button.

Thank you for your reply. I have tried the manual mode. It doesn't work. I think the problem is my PC could not recognize the USB device, rather than the inability to download firmware via USB.

**Comment by undefinedcodezhong** [comment]
@espressif2022 这个不确定，因为是淘的板子，别人开发一半不做了，我接了板子想搞自己的程序。我尝试按照这里的[Windows系统更新固件方法](https://github.com/espressif/esp-box/blob/master/docs/firmware_update_cn.md#windows-%E7%B3%BB%E7%BB%9F%E6%9B%B4%E6%96%B0%E5%9B%BA%E4%BB%B6%E8%AF%B4%E6%98%8E)，不过使用usb2uart模块来代替typeC，但是卡在了“等待上电同步”这里了。

设备管理器能看到usb2uart的com口：
![414ae48fb5aae44b89415f54c0dda76](https://github.com/espressif/esp-box/assets/40236765/cc8f0508-9501-4771-bf49-2a6689a701a1)
flash_download_tool下载图示：
![2afef29a70c0ebaae52097949c40391](https://github.com/espressif/esp-box/assets/40236765/c202e277-68e3-4033-ae95-c6000f7e7b44)

**Comment by undefinedcodezhong** [comment]
@espressif2022 换了台电脑，还是用USB转串口的方式，现在能下载固件了，但是连接USB不能正确识别的问题还是存在，这个有没有解决方案，毕竟有USB开发也会方便很多，串口烧录程序总是麻烦一些。

**Comment by espressif2022** [comment]
> @espressif2022 换了台电脑，还是用USB转串口的方式，现在能下载固件了，但是连接USB不能正确识别的问题还是存在，这个有没有解决方案，毕竟有USB开发也会方便很多，串口烧录程序总是麻烦一些。

我看你这识别的是 USB 设备，不是串口设备。USB转串口，你这怎么接的？

**Comment by undefinedcodezhong** [comment]
@espressif2022 最后是换了一个CH340 的USB转TTL串口，通过uart下载的，能成功下载固件的那次忘记保留端口设备截图了。Type-C直连识别不了，会显示未识别设备。

**Comment by undefinedcodezhong** [comment]
@espressif2022 ok了，换了条线，终于能typeC直连了
