### ISSUE TITLE
The Home Assistant support.  (AEGHB-359)

### ISSUE THREAD

**Issue by ialexyi** [espressif/esp-box#90]
Please add an example for Home Assistant.

**Comment by ESP-Mars** [comment]
Thanks for your suggestion, we have maker has ported Home Assistant to ESP, please refer to https://heywillow.io

**Comment by ESP-Mars** [comment]
As there's already an great project created for 'Home Assistant' platform using the ESP-BOX series boards [here](https://github.com/toverainc/willow) through ESP-BOX serials board. We are temporarily closing the issue. If you have any additional questions or concerns, please don't hesitate to reopen it.
