### ISSUE TITLE
can box connect with USB device (u-disc)? how to do that?  (AEGHB-360)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-box#91]
the question as title, i want save data into USB storage.
thanks!

**Comment by espressif2022** [comment]
you can refer to this: https://github.com/espressif/esp-dev-kits/tree/master/esp32-s3-lcd-ev-board/examples/usb_msc_file_sys

**Comment by alibukharai** [comment]
@fatsheep2020 Additionally, you can explore this example implementation that utilizes TinyUF2. https://github.com/espressif/esp-box/tree/master/examples/chatgpt_demo/factory_nvs

**Comment by fatsheep2020** [comment]
> 

thanks!  but what used is Arduino environment, is there any example on that?

**Comment by ESP-Mars** [comment]
> thanks! but what used is Arduino environment, is there any example on that?

USB has not been ported to the Arduino environment yet.

**Comment by ESP-Mars** [comment]
We are temporarily closing the issue, and any updates related to this requirement will be communicated here. If you have further questions or concerns, please feel free to reopen the issue.
