### ISSUE TITLE
[Help]how to download/upload file from SPIFFS (AEGHB-366)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-box#92]
when i want upload many files to SPIFFS and download it to check, how to do that?

Thanks!

**Comment by espressif2022** [comment]
> when i want upload many files to SPIFFS and download it to check, how to do that?
> 
> Thanks!

Can you give a more detailed description of the requirements?
What interface, USB, wifi?

**Comment by fatsheep2020** [comment]
yes, the communication interface is usb or wifi, both are ok. just use SPIFFS(the flash file system in Box) to save files, and also can use PC to download check the files content.
Thanks!

**Comment by espressif2022** [comment]
> yes, the communication interface is usb or wifi, both are ok. just use SPIFFS(the flash file system in Box) to save files, and also can use PC to download check the files content. Thanks!

You can refer to this two demos in ESP-IDF:
Wi-Fi: esp-idf/examples/protocols/http_server/file_serving
USB: esp-idf/examples/peripherals/usb/device/tusb_msc
If you want to verify whether the file is correct, can't you do a local MD5 verification in the box?

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
