### ISSUE TITLE
GPT Demo on M5Stack CoreS3 ? (AEGHB-375)

### ISSUE THREAD

**Issue by recrudesce** [espressif/esp-box#97]
Not an issue, more a question.

Would your GPT demo for your ESP32-S3-BOX potentially work on an M5Stack CoreS3 ?  Looks like essentially the same product...

**Comment by espressif2022** [comment]
Hello, M5Stack Core3 is not maintained by us，but I think you can try to port it yourself.
I think It worked.

**Comment by recrudesce** [comment]
I know it's not maintained or made by you, just wondering if the underlying hardware would be similar.  I'll try a port and see what happens :)

**Comment by espressif2022** [comment]
> I know it's not maintained or made by you, just wondering if the underlying hardware would be similar. I'll try a port and see what happens :)

It's similar, they tried our `components_esp_sr` last week, we add a wakenet(`HI, I'm five`) for them.

**Comment by ESP-Mars** [comment]
Temporarily closed due to the extended period of time with no response. Should you have additional questions or concerns, don't hesitate to reopen the issue.
